// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ConfigEncabezado.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ConfigEncabezado_ClassInterface
	{
		int Index { get; set; }
		string Texto { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ConfigEncabezado 
		: MInput
		, IMI_ConfigEncabezado_ClassInterface
	{
		public int Index { get; set; }
		public string Texto { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0508, extension, list);
				Append_N(list, Index, 3, 0, false);
				Append_RT(list, Texto, -1, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ConfigEncabezado_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ConfigEncabezado  
		: MOutput
		, IMO_ConfigEncabezado_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ConfigEncabezado_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ConfigEncabezado_ClassInterface Input { get; }
		IMO_ConfigEncabezado_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ConfigEncabezado 
	    : CMD_Generic
		, ICMD_ConfigEncabezado_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ConfigEncabezado"; }}
		public override int Opcode { get { return 0x0508; }}
		public override string Description { get { return "Configura las lineas de encabezado."; }}

		public IMI_ConfigEncabezado_ClassInterface Input { get; protected set; }
		public IMO_ConfigEncabezado_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ConfigEncabezado();
			Output = new MO_ConfigEncabezado();
		}

		// Ctor
		public CMD_ConfigEncabezado()
		{
			SetDefaults();
		}
	}

}
