// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ObtenerEncabezado.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ObtenerEncabezado_ClassInterface
	{
		int Index { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ObtenerEncabezado 
		: MInput
		, IMI_ObtenerEncabezado_ClassInterface
	{
		public int Index { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0509, extension, list);
				Append_N(list, Index, 3, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ObtenerEncabezado_ClassInterface
	{
		string Texto { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ObtenerEncabezado  
		: MOutput
		, IMO_ObtenerEncabezado_ClassInterface
	{
		public string Texto { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Texto = Extract_RT(data, -1, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ObtenerEncabezado_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ObtenerEncabezado_ClassInterface Input { get; }
		IMO_ObtenerEncabezado_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ObtenerEncabezado 
	    : CMD_Generic
		, ICMD_ObtenerEncabezado_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerEncabezado"; }}
		public override int Opcode { get { return 0x0509; }}
		public override string Description { get { return "Obtiene el texto configurado en una línea determinada del encabezado."; }}

		public IMI_ObtenerEncabezado_ClassInterface Input { get; protected set; }
		public IMO_ObtenerEncabezado_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ObtenerEncabezado();
			Output = new MO_ObtenerEncabezado();
		}

		// Ctor
		public CMD_ObtenerEncabezado()
		{
			SetDefaults();
		}
	}

}
