// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ConfigRedEstablece.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ConfigRedEstablece_ClassInterface
	{
		string IP { get; set; }
		string Mask { get; set; }
		string Gateway { get; set; }
		bool UsaDHCP { get; set; }
		bool Reset { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ConfigRedEstablece 
		: MInput
		, IMI_ConfigRedEstablece_ClassInterface
	{
		public string IP { get; set; }
		public string Mask { get; set; }
		public string Gateway { get; set; }
		public bool UsaDHCP { get; set; }
		public bool Reset { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(UsaDHCP) extension |= 0x01;
				if(Reset) extension |= 0x02;
				SetOpcode(0x05C1, extension, list);
				Append_P(list, IP, 19, 0, true);
				Append_P(list, Mask, 19, 0, true);
				Append_P(list, Gateway, 19, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ConfigRedEstablece_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ConfigRedEstablece  
		: MOutput
		, IMO_ConfigRedEstablece_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ConfigRedEstablece_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ConfigRedEstablece_ClassInterface Input { get; }
		IMO_ConfigRedEstablece_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ConfigRedEstablece 
	    : CMD_Generic
		, ICMD_ConfigRedEstablece_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ConfigRedEstablece"; }}
		public override int Opcode { get { return 0x05C1; }}
		public override string Description { get { return "Establece los parámetros mínimos para iniciar una conexión de red."; }}

		public IMI_ConfigRedEstablece_ClassInterface Input { get; protected set; }
		public IMO_ConfigRedEstablece_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ConfigRedEstablece();
			Output = new MO_ConfigRedEstablece();
		}

		// Ctor
		public CMD_ConfigRedEstablece()
		{
			SetDefaults();
		}
	}

}
