// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ConfigRespIVA.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ConfigRespIVA_ClassInterface
	{
		string ResponCode { get; set; }
		int TipoTicket { get; set; }
		string Leyenda { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ConfigRespIVA 
		: MInput
		, IMI_ConfigRespIVA_ClassInterface
	{
		public string ResponCode { get; set; }
		public int TipoTicket { get; set; }
		public string Leyenda { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0504, extension, list);
				Append_P(list, ResponCode, 1, 0, false);
				Append_N(list, TipoTicket, 1, 0, true);
				Append_RT(list, Leyenda, 60, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ConfigRespIVA_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ConfigRespIVA  
		: MOutput
		, IMO_ConfigRespIVA_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ConfigRespIVA_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ConfigRespIVA_ClassInterface Input { get; }
		IMO_ConfigRespIVA_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ConfigRespIVA 
	    : CMD_Generic
		, ICMD_ConfigRespIVA_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ConfigRespIVA"; }}
		public override int Opcode { get { return 0x0504; }}
		public override string Description { get { return "Configura la responsabilidad que tendrá el usuario frente al IVA."; }}

		public IMI_ConfigRespIVA_ClassInterface Input { get; protected set; }
		public IMO_ConfigRespIVA_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ConfigRespIVA();
			Output = new MO_ConfigRespIVA();
		}

		// Ctor
		public CMD_ConfigRespIVA()
		{
			SetDefaults();
		}
	}

}
