// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ConfigRedLee.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ConfigRedLee_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ConfigRedLee 
		: MInput
		, IMI_ConfigRedLee_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x05C2, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ConfigRedLee_ClassInterface
	{
		bool UsaDHCP { get; set; }
		string IP { get; set; }
		string Mask { get; set; }
		string Gateway { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ConfigRedLee  
		: MOutput
		, IMO_ConfigRedLee_ClassInterface
	{
		public bool UsaDHCP { get; set; }
		public string IP { get; set; }
		public string Mask { get; set; }
		public string Gateway { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					UsaDHCP = Extract_Y(data, 1, false);
					IP = Extract_P(data, 19, true);
					Mask = Extract_P(data, 19, true);
					Gateway = Extract_P(data, 19, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ConfigRedLee_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ConfigRedLee_ClassInterface Input { get; }
		IMO_ConfigRedLee_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ConfigRedLee 
	    : CMD_Generic
		, ICMD_ConfigRedLee_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ConfigRedLee"; }}
		public override int Opcode { get { return 0x05C2; }}
		public override string Description { get { return "Obtiene los parámetros configurados para iniciar una conexión de red."; }}

		public IMI_ConfigRedLee_ClassInterface Input { get; protected set; }
		public IMO_ConfigRedLee_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ConfigRedLee();
			Output = new MO_ConfigRedLee();
		}

		// Ctor
		public CMD_ConfigRedLee()
		{
			SetDefaults();
		}
	}

}
