// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ConfigFechaHora.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ConfigFechaHora_ClassInterface
	{
		int Fecha { get; set; }
		int Hora { get; set; }
		CFH_TimeZone TimeZone { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ConfigFechaHora 
		: MInput
		, IMI_ConfigFechaHora_ClassInterface
	{
		public int Fecha { get; set; }
		public int Hora { get; set; }
		public CFH_TimeZone TimeZone { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				extension |= (((int) TimeZone) & 0x0003);
				SetOpcode(0x0501, extension, list);
				Append_D(list, Fecha, 6, 0, false);
				Append_T(list, Hora, 6, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ConfigFechaHora_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ConfigFechaHora  
		: MOutput
		, IMO_ConfigFechaHora_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ConfigFechaHora_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ConfigFechaHora_ClassInterface Input { get; }
		IMO_ConfigFechaHora_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ConfigFechaHora 
	    : CMD_Generic
		, ICMD_ConfigFechaHora_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ConfigFechaHora"; }}
		public override int Opcode { get { return 0x0501; }}
		public override string Description { get { return "Establece la fecha y hora en el reloj interno del controlador fiscal."; }}

		public IMI_ConfigFechaHora_ClassInterface Input { get; protected set; }
		public IMO_ConfigFechaHora_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ConfigFechaHora();
			Output = new MO_ConfigFechaHora();
		}

		// Ctor
		public CMD_ConfigFechaHora()
		{
			SetDefaults();
		}
	}

	public enum CFH_TimeZone 
	{
		Normal = 0,	// 00
		HorarioVeranoSi = 1,	// 01
	};

}
