// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ObtenerDatosFiscalizacion.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ObtenerDatosFiscalizacion_ClassInterface
	{
		bool Print { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ObtenerDatosFiscalizacion 
		: MInput
		, IMI_ObtenerDatosFiscalizacion_ClassInterface
	{
		public bool Print { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Print) extension |= 0x01;
				SetOpcode(0x0507, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ObtenerDatosFiscalizacion_ClassInterface
	{
		string RazonSocial { get; set; }
		string Cuit { get; set; }
		int PtoVta { get; set; }
		string RespIVA { get; set; }
		string TipoTicket { get; set; }
		int TasaIVA { get; set; }
		int FechaFiscal { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ObtenerDatosFiscalizacion  
		: MOutput
		, IMO_ObtenerDatosFiscalizacion_ClassInterface
	{
		public string RazonSocial { get; set; }
		public string Cuit { get; set; }
		public int PtoVta { get; set; }
		public string RespIVA { get; set; }
		public string TipoTicket { get; set; }
		public int TasaIVA { get; set; }
		public int FechaFiscal { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					RazonSocial = Extract_P(data, 50, false);
					Cuit = Extract_P(data, 13, false);
					PtoVta = Extract_N(data, 5, false);
					RespIVA = Extract_P(data, 1, false);
					TipoTicket = Extract_P(data, 2, false);
					TasaIVA = Extract_N(data, 4, false);
					FechaFiscal = Extract_D(data, 6, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ObtenerDatosFiscalizacion_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ObtenerDatosFiscalizacion_ClassInterface Input { get; }
		IMO_ObtenerDatosFiscalizacion_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ObtenerDatosFiscalizacion 
	    : CMD_Generic
		, ICMD_ObtenerDatosFiscalizacion_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerDatosFiscalizacion"; }}
		public override int Opcode { get { return 0x0507; }}
		public override string Description { get { return "Obtiene los datos de fiscalización configurados en el controlador fiscal."; }}

		public IMI_ObtenerDatosFiscalizacion_ClassInterface Input { get; protected set; }
		public IMO_ObtenerDatosFiscalizacion_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ObtenerDatosFiscalizacion();
			Output = new MO_ObtenerDatosFiscalizacion();
		}

		// Ctor
		public CMD_ObtenerDatosFiscalizacion()
		{
			SetDefaults();
		}
	}

}
