// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_LogoContenido.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_LogoContenido_ClassInterface
	{
		string Datos { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_LogoContenido 
		: MInput
		, IMI_LogoContenido_ClassInterface
	{
		public string Datos { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0531, extension, list);
				Append_P(list, Datos, 200, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_LogoContenido_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_LogoContenido  
		: MOutput
		, IMO_LogoContenido_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_LogoContenido_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_LogoContenido_ClassInterface Input { get; }
		IMO_LogoContenido_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_LogoContenido 
	    : CMD_Generic
		, ICMD_LogoContenido_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "LogoContenido"; }}
		public override int Opcode { get { return 0x0531; }}
		public override string Description { get { return "Envía el conjunto de datos que definen el logo."; }}

		public IMI_LogoContenido_ClassInterface Input { get; protected set; }
		public IMO_LogoContenido_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_LogoContenido();
			Output = new MO_LogoContenido();
		}

		// Ctor
		public CMD_LogoContenido()
		{
			SetDefaults();
		}
	}

}
