// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_DisplayConfig.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_DisplayConfig_ClassInterface
	{
		int Timeout { get; set; }
		bool Subtotal { get; set; }
		DC_Item Item { get; set; }
		DC_Cierre Cierre { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_DisplayConfig 
		: MInput
		, IMI_DisplayConfig_ClassInterface
	{
		public int Timeout { get; set; }
		public bool Subtotal { get; set; }
		public DC_Item Item { get; set; }
		public DC_Cierre Cierre { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Subtotal) extension |= 0x04;
				extension |= (((int) Item) & 0x0003);
				extension |= ((((int) Cierre) & 0x0003) << 8);
				SetOpcode(0x05D1, extension, list);
				Append_N(list, Timeout, 3, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_DisplayConfig_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_DisplayConfig  
		: MOutput
		, IMO_DisplayConfig_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_DisplayConfig_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_DisplayConfig_ClassInterface Input { get; }
		IMO_DisplayConfig_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_DisplayConfig 
	    : CMD_Generic
		, ICMD_DisplayConfig_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DisplayConfig"; }}
		public override int Opcode { get { return 0x05D1; }}
		public override string Description { get { return "Configura el comportamiento automático del display."; }}

		public IMI_DisplayConfig_ClassInterface Input { get; protected set; }
		public IMO_DisplayConfig_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_DisplayConfig();
			Output = new MO_DisplayConfig();
		}

		// Ctor
		public CMD_DisplayConfig()
		{
			SetDefaults();
		}
	}

	public enum DC_Item 
	{
		ItemNada = 0,	// 00
		CantXUnit = 1,	// 01
		ItemUnitario = 2,	// 10
		ItemTotal = 3,	// 11
	};

	public enum DC_Cierre 
	{
		CierreNada = 0,	// 00
		CierreTotal = 1,	// 01
		CierreVuelto = 2,	// 10
	};

}
