// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ObtenerDensidadImpresion.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ObtenerDensidadImpresion_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ObtenerDensidadImpresion 
		: MInput
		, IMI_ObtenerDensidadImpresion_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0778, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ObtenerDensidadImpresion_ClassInterface
	{
		int Densidad { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ObtenerDensidadImpresion  
		: MOutput
		, IMO_ObtenerDensidadImpresion_ClassInterface
	{
		public int Densidad { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Densidad = Extract_N(data, 2, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ObtenerDensidadImpresion_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ObtenerDensidadImpresion_ClassInterface Input { get; }
		IMO_ObtenerDensidadImpresion_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ObtenerDensidadImpresion 
	    : CMD_Generic
		, ICMD_ObtenerDensidadImpresion_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Compatible; }}
		public override string Nombre { get { return "ObtenerDensidadImpresion"; }}
		public override int Opcode { get { return 0x0778; }}
		public override string Description { get { return "Obtiene la densidad de impresión configurada."; }}

		public IMI_ObtenerDensidadImpresion_ClassInterface Input { get; protected set; }
		public IMO_ObtenerDensidadImpresion_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ObtenerDensidadImpresion();
			Output = new MO_ObtenerDensidadImpresion();
		}

		// Ctor
		public CMD_ObtenerDensidadImpresion()
		{
			SetDefaults();
		}
	}

}
