// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_NCGetUltimoCierre.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_NCGetUltimoCierre_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_NCGetUltimoCierre 
		: MInput
		, IMI_NCGetUltimoCierre_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0D10, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_NCGetUltimoCierre_ClassInterface
	{
		int NumTicket { get; set; }
		string Tipo { get; set; }
		decimal Total { get; set; }
		decimal Iva { get; set; }
		decimal Vuelto { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_NCGetUltimoCierre  
		: MOutput
		, IMO_NCGetUltimoCierre_ClassInterface
	{
		public int NumTicket { get; set; }
		public string Tipo { get; set; }
		public decimal Total { get; set; }
		public decimal Iva { get; set; }
		public decimal Vuelto { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					NumTicket = Extract_N(data, 8, true);
					Tipo = Extract_L(data, 1, true);
					Total = Extract_N(data, 10, 2, true);
					Iva = Extract_N(data, 10, 2, true);
					Vuelto = Extract_N(data, 10, 2, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_NCGetUltimoCierre_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_NCGetUltimoCierre_ClassInterface Input { get; }
		IMO_NCGetUltimoCierre_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_NCGetUltimoCierre 
	    : CMD_Generic
		, ICMD_NCGetUltimoCierre_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "NCGetUltimoCierre"; }}
		public override int Opcode { get { return 0x0D10; }}
		public override string Description { get { return "Obtiene información sobre la respuesta enviada por el comando de cierre dela última nota de crédito cerrado exitosamente."; }}

		public IMI_NCGetUltimoCierre_ClassInterface Input { get; protected set; }
		public IMO_NCGetUltimoCierre_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_NCGetUltimoCierre();
			Output = new MO_NCGetUltimoCierre();
		}

		// Ctor
		public CMD_NCGetUltimoCierre()
		{
			SetDefaults();
		}
	}

}
