// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_NCSubtotal.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_NCSubtotal_ClassInterface
	{
		bool Print { get; set; }
		NCS_TipoSubtotal TipoSubtotal { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_NCSubtotal 
		: MInput
		, IMI_NCSubtotal_ClassInterface
	{
		public bool Print { get; set; }
		public NCS_TipoSubtotal TipoSubtotal { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Print) extension |= 0x01;
				extension |= ((((int) TipoSubtotal) & 0x0003) << 2);
				SetOpcode(0x0D03, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_NCSubtotal_ClassInterface
	{
		decimal MontoBruto { get; set; }
		decimal MontoNeto { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_NCSubtotal  
		: MOutput
		, IMO_NCSubtotal_ClassInterface
	{
		public decimal MontoBruto { get; set; }
		public decimal MontoNeto { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					MontoBruto = Extract_N(data, 12, 4, true);
					MontoNeto = Extract_N(data, 12, 4, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_NCSubtotal_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_NCSubtotal_ClassInterface Input { get; }
		IMO_NCSubtotal_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_NCSubtotal 
	    : CMD_Generic
		, ICMD_NCSubtotal_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "NCSubtotal"; }}
		public override int Opcode { get { return 0x0D03; }}
		public override string Description { get { return "Calcula los totales de la operación actual y lo imprime y/o devuelve en la respuesta."; }}

		public IMI_NCSubtotal_ClassInterface Input { get; protected set; }
		public IMO_NCSubtotal_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_NCSubtotal();
			Output = new MO_NCSubtotal();
		}

		// Ctor
		public CMD_NCSubtotal()
		{
			SetDefaults();
		}
	}

	public enum NCS_TipoSubtotal 
	{
		Bruto = 0,	// 00
		Neto = 1,	// 01
		Bruto_Neto = 2,	// 10
		Nada = 3,	// 11
	};

}
