// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_NCSetConfig.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_NCSetConfig_ClassInterface
	{
		bool AddBlank { get; set; }
		bool PrintDOM { get; set; }
		bool PrintFANT { get; set; }
		bool PrintIB { get; set; }
		bool PrintHeader { get; set; }
		bool AddBlankTotal { get; set; }
		bool PrintQR { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_NCSetConfig 
		: MInput
		, IMI_NCSetConfig_ClassInterface
	{
		public bool AddBlank { get; set; }
		public bool PrintDOM { get; set; }
		public bool PrintFANT { get; set; }
		public bool PrintIB { get; set; }
		public bool PrintHeader { get; set; }
		public bool AddBlankTotal { get; set; }
		public bool PrintQR { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(AddBlank) extension |= 0x04;
				if(PrintDOM) extension |= 0x40;
				if(PrintFANT) extension |= 0x80;
				if(PrintIB) extension |= 0x100;
				if(PrintHeader) extension |= 0x400;
				if(AddBlankTotal) extension |= 0x1000;
				if(PrintQR) extension |= 0x4000;
				SetOpcode(0x0D08, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_NCSetConfig_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_NCSetConfig  
		: MOutput
		, IMO_NCSetConfig_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_NCSetConfig_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_NCSetConfig_ClassInterface Input { get; }
		IMO_NCSetConfig_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_NCSetConfig 
	    : CMD_Generic
		, ICMD_NCSetConfig_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "NCSetConfig"; }}
		public override int Opcode { get { return 0x0D08; }}
		public override string Description { get { return "Configura las preferencias para TODAS las notas de crédito que se emitan."; }}

		public IMI_NCSetConfig_ClassInterface Input { get; protected set; }
		public IMO_NCSetConfig_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_NCSetConfig();
			Output = new MO_NCSetConfig();
		}

		// Ctor
		public CMD_NCSetConfig()
		{
			SetDefaults();
		}
	}

}
