// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_NCPago.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_NCPago_ClassInterface
	{
		string PagoDescExtra1 { get; set; }
		string PagoDescExtra2 { get; set; }
		int Cuotas { get; set; }
		string DetaAdic { get; set; }
		string DetaCupon { get; set; }
		CodMedioDePago Codigo { get; set; }
		decimal Monto { get; set; }
		bool Tipo { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_NCPago 
		: MInput
		, IMI_NCPago_ClassInterface
	{
		public string PagoDescExtra1 { get; set; }
		public string PagoDescExtra2 { get; set; }
		public int Cuotas { get; set; }
		public string DetaAdic { get; set; }
		public string DetaCupon { get; set; }
		public CodMedioDePago Codigo { get; set; }
		public decimal Monto { get; set; }
		public bool Tipo { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Tipo) extension |= 0x01;
				SetOpcode(0x0D05, extension, list);
				Append_RT(list, PagoDescExtra1, -1, 0, true);
				Append_RT(list, PagoDescExtra2, -1, 0, true);
				Append_N(list, Cuotas, 3, 0, true);
				Append_RT(list, DetaAdic, -1, 0, true);
				Append_RT(list, DetaCupon, -1, 0, true);
				Append_N(list, (int)Codigo, 2, 0, false);
				Append_N(list, Monto, 10, 2, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_NCPago_ClassInterface
	{
		decimal Pendiente { get; set; }
		decimal Vuelto { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_NCPago  
		: MOutput
		, IMO_NCPago_ClassInterface
	{
		public decimal Pendiente { get; set; }
		public decimal Vuelto { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Pendiente = Extract_N(data, 10, 2, false);
					Vuelto = Extract_N(data, 10, 2, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_NCPago_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_NCPago_ClassInterface Input { get; }
		IMO_NCPago_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_NCPago 
	    : CMD_Generic
		, ICMD_NCPago_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "NCPago"; }}
		public override int Opcode { get { return 0x0D05; }}
		public override string Description { get { return "Aplica un pago (o cancelacion) al documento en curso."; }}

		public IMI_NCPago_ClassInterface Input { get; protected set; }
		public IMO_NCPago_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_NCPago();
			Output = new MO_NCPago();
		}

		// Ctor
		public CMD_NCPago()
		{
			SetDefaults();
		}
	}

}
