// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_TKOtroTributo.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_TKOtroTributo_ClassInterface
	{
		string Descrip { get; set; }
		decimal Monto { get; set; }
		int TasaIVA { get; set; }
		bool Accion { get; set; }
		bool RetSubtot { get; set; }
		TKOT_Tipo Tipo { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_TKOtroTributo 
		: MInput
		, IMI_TKOtroTributo_ClassInterface
	{
		public string Descrip { get; set; }
		public decimal Monto { get; set; }
		public int TasaIVA { get; set; }
		public bool Accion { get; set; }
		public bool RetSubtot { get; set; }
		public TKOT_Tipo Tipo { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Accion) extension |= 0x01;
				if(RetSubtot) extension |= 0x400;
				extension |= ((((int) Tipo) & 0x000F) << 6);
				SetOpcode(0x0A20, extension, list);
				Append_RT(list, Descrip, -1, 0, false);
				Append_N(list, Monto, 10, 2, false);
				Append_N(list, TasaIVA, 4, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_TKOtroTributo_ClassInterface
	{
		decimal Subtotal { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_TKOtroTributo  
		: MOutput
		, IMO_TKOtroTributo_ClassInterface
	{
		public decimal Subtotal { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Subtotal = Extract_N(data, 10, 2, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_TKOtroTributo_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_TKOtroTributo_ClassInterface Input { get; }
		IMO_TKOtroTributo_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_TKOtroTributo 
	    : CMD_Generic
		, ICMD_TKOtroTributo_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "TKOtroTributo"; }}
		public override int Opcode { get { return 0x0A20; }}
		public override string Description { get { return "Aplica un tributo adicional la operación en curso."; }}

		public IMI_TKOtroTributo_ClassInterface Input { get; protected set; }
		public IMO_TKOtroTributo_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_TKOtroTributo();
			Output = new MO_TKOtroTributo();
		}

		// Ctor
		public CMD_TKOtroTributo()
		{
			SetDefaults();
		}
	}

	public enum TKOT_Tipo 
	{
		ImpNacional = 2,	// 0010
		ImpProvincial = 3,	// 0011
		ImpMunicipal = 5,	// 0101
		ImpInterno = 6,	// 0110
		ImpIngBrutos = 7,	// 0111
		Otros = 9,	// 1001
	};

}
