// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_TKSubtotal.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Ticket
{
	public class MI_TKSubtotal : MInput
	{

		[Category("Extension")]
		[Description(
			"Imprime el subtotal\n" +
			"false: No, true: Si")]
		public bool Print { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Print) extension |= 0x01;
				SetOpcode(0x0A03, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_TKSubtotal  : MOutput
	{

		[Description("Subtotal parcial del ticket (bruto)."), Category("Datos"), ReadOnly(true)]
		public decimal Monto { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Monto = Extract_N(data, 12, 2, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_TKSubtotal 
	    : CMD_CommandBase<MI_TKSubtotal, MO_TKSubtotal>
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "TKSubtotal"; }}
		public override int Opcode { get { return 0x0A03; }}
		public override string Description { get { return "Calcula los totales del ticket actual y lo imprime y/o devuelve en la respuesta."; }}

		// Ctor
		public CMD_TKSubtotal()
		{
			Input = new MI_TKSubtotal();
			Output = new MO_TKSubtotal();
		}
	}
}
