// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_DNL_RangoFechas.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_DNL_RangoFechas_ClassInterface
	{
		int FechaDesde { get; set; }
		int FechaHasta { get; set; }
		bool Zipeado { get; set; }
		bool Pendrive { get; set; }
		DNLRF_Selector Selector { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_DNL_RangoFechas 
		: MInput
		, IMI_DNL_RangoFechas_ClassInterface
	{
		public int FechaDesde { get; set; }
		public int FechaHasta { get; set; }
		public bool Zipeado { get; set; }
		public bool Pendrive { get; set; }
		public DNLRF_Selector Selector { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Zipeado) extension |= 0x01;
				if(Pendrive) extension |= 0x08;
				extension |= ((((int) Selector) & 0x0003) << 1);
				SetOpcode(0x0951, extension, list);
				Append_D(list, FechaDesde, 6, 0, false);
				Append_D(list, FechaHasta, 6, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_DNL_RangoFechas_ClassInterface
	{
		string NomArchivo { get; set; }
		int Largo { get; set; }
		bool Vacio { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_DNL_RangoFechas  
		: MOutput
		, IMO_DNL_RangoFechas_ClassInterface
	{
		public string NomArchivo { get; set; }
		public int Largo { get; set; }
		public bool Vacio { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					NomArchivo = Extract_P(data, -1, false);
					Largo = Extract_N(data, 10, false);
					Vacio = Extract_Y(data, 1, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_DNL_RangoFechas_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_DNL_RangoFechas_ClassInterface Input { get; }
		IMO_DNL_RangoFechas_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_DNL_RangoFechas 
	    : CMD_Generic
		, ICMD_DNL_RangoFechas_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DNL_RangoFechas"; }}
		public override int Opcode { get { return 0x0951; }}
		public override string Description { get { return "Descarga información digital, indicando el rango de fechas para las que se requiere la información."; }}

		public IMI_DNL_RangoFechas_ClassInterface Input { get; protected set; }
		public IMO_DNL_RangoFechas_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_DNL_RangoFechas();
			Output = new MO_DNL_RangoFechas();
		}

		// Ctor
		public CMD_DNL_RangoFechas()
		{
			SetDefaults();
		}
	}

	public enum DNLRF_Selector 
	{
		CTD = 0,	// 00
		DUPLI_A = 1,	// 01
		RESUMEN = 2,	// 10
	};

}
