// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_DNFH1Info.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.DNFH_Genericos
{
	public class MI_DNFH1Info : MInput
	{

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0E0A, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_DNFH1Info  : MOutput
	{

		[Description("Número del documento no fiscal en curso."), Category("Datos"), ReadOnly(true)]
		public int Numero { get; set; }

		[Description("Cantidad de líneas actualmente impresas."), Category("Datos"), ReadOnly(true)]
		public int Lineas { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Numero = Extract_N(data, 5, false);
					Lineas = Extract_N(data, 8, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_DNFH1Info 
	    : CMD_CommandBase<MI_DNFH1Info, MO_DNFH1Info>
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "DNFH1Info"; }}
		public override int Opcode { get { return 0x0E0A; }}
		public override string Description { get { return "Obtiene información sobre el DNFH actualmente en curso."; }}

		// Ctor
		public CMD_DNFH1Info()
		{
			Input = new MI_DNFH1Info();
			Output = new MO_DNFH1Info();
		}
	}
}
