// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_DNFH1ObtienePreferencias.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.DNFH_Genericos
{
	public class MI_DNFH1ObtienePreferencias : MInput
	{

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0E09, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_DNFH1ObtienePreferencias  : MOutput
	{

		[Description("Reservado."), Category("Datos"), ReadOnly(true)]
		public string Reservado1 { get; set; }

		[Description("Reservado."), Category("Datos"), ReadOnly(true)]
		public string Reservado2 { get; set; }

		[Description("Indica si imprime o no la Razón Social en el encabezamiento de un DNFH."), Category("Datos"), ReadOnly(true)]
		public bool RazonSocial { get; set; }

		[Description("Indica si imprime o no el Punto de Venta en el encabezamiento de un DNFH."), Category("Datos"), ReadOnly(true)]
		public bool PtoVta { get; set; }

		[Description("Reservado."), Category("Datos"), ReadOnly(true)]
		public string Reservado3 { get; set; }

		[Description("Reservado."), Category("Datos"), ReadOnly(true)]
		public string Reservado4 { get; set; }

		[Description("Reservado."), Category("Datos"), ReadOnly(true)]
		public string Reservado5 { get; set; }

		[Description("Indica si imprime o no las líneas de Fantasía en el encabezamiento de un DNFH."), Category("Datos"), ReadOnly(true)]
		public bool Fantasia { get; set; }

		[Description("Indica si imprime o no las líneas de Ingresos Brutos en el encabezamiento de un DNFH."), Category("Datos"), ReadOnly(true)]
		public bool IIBB { get; set; }

		[Description("Indica si imprime o no las líneas de Inicio de Actividades en el encabezamiento de un DNFH."), Category("Datos"), ReadOnly(true)]
		public bool IniAct { get; set; }

		[Description("Indica si imprime o no las líneas de Logo en el encabezamiento de un DNFH."), Category("Datos"), ReadOnly(true)]
		public bool Logo { get; set; }

		[Description("Indica si imprime o no las líneas de Domicilio Comercial en el encabezamiento de un DNFH."), Category("Datos"), ReadOnly(true)]
		public bool DomComercial { get; set; }

		[Description("Indica si imprime o no las líneas de datos fiscales en el encabezamiento de un DNFH."), Category("Datos"), ReadOnly(true)]
		public bool DataFiscal { get; set; }

		[Description("Reservado."), Category("Datos"), ReadOnly(true)]
		public string Reservado6 { get; set; }

		[Description("Reservado."), Category("Datos"), ReadOnly(true)]
		public string Reservado7 { get; set; }

		[Description("Reservado."), Category("Datos"), ReadOnly(true)]
		public string Reservado8 { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Reservado1 = Extract_A(data, 1, false);
					Reservado2 = Extract_A(data, 1, false);
					RazonSocial = Extract_Y(data, 1, false);
					PtoVta = Extract_Y(data, 1, false);
					Reservado3 = Extract_A(data, 1, false);
					Reservado4 = Extract_A(data, 1, false);
					Reservado5 = Extract_A(data, 1, false);
					Fantasia = Extract_Y(data, 1, false);
					IIBB = Extract_Y(data, 1, false);
					IniAct = Extract_Y(data, 1, false);
					Logo = Extract_Y(data, 1, false);
					DomComercial = Extract_Y(data, 1, false);
					DataFiscal = Extract_Y(data, 1, false);
					Reservado6 = Extract_A(data, 1, false);
					Reservado7 = Extract_A(data, 1, false);
					Reservado8 = Extract_A(data, 1, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_DNFH1ObtienePreferencias 
	    : CMD_CommandBase<MI_DNFH1ObtienePreferencias, MO_DNFH1ObtienePreferencias>
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "DNFH1ObtienePreferencias"; }}
		public override int Opcode { get { return 0x0E09; }}
		public override string Description { get { return "Devuelve las preferencias configuradas para los Documentos No fiscales Homologados."; }}

		// Ctor
		public CMD_DNFH1ObtienePreferencias()
		{
			Input = new MI_DNFH1ObtienePreferencias();
			Output = new MO_DNFH1ObtienePreferencias();
		}
	}
}
