// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_DNFTarjeta.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_DNFTarjeta_ClassInterface
	{
		string LTipo { get; set; }
		string LTarjeta { get; set; }
		string LCliente { get; set; }
		int LVencim { get; set; }
		string LEstab { get; set; }
		string LCupon { get; set; }
		string LComprob { get; set; }
		string LAutoriz { get; set; }
		string LOperacion { get; set; }
		decimal LImporte { get; set; }
		int LCuotas { get; set; }
		string LMoneda { get; set; }
		string LTerminal { get; set; }
		string LLote { get; set; }
		string LTpv { get; set; }
		string LSucu { get; set; }
		string LOpe { get; set; }
		string LReferen { get; set; }
		string LLibre1 { get; set; }
		string LLibre2 { get; set; }
		string LLibre3 { get; set; }
		string LLibre4 { get; set; }
		string LLibre5 { get; set; }
		string LLibre6 { get; set; }
		int ReempColaNum1 { get; set; }
		string ReempColaTexto1 { get; set; }
		int ReempColaNum2 { get; set; }
		string ReempColaTexto2 { get; set; }
		int ReempColaNum3 { get; set; }
		string ReempColaTexto3 { get; set; }
		bool Cut { get; set; }
		bool PrintDomi { get; set; }
		bool PrintDoc { get; set; }
		bool PrintFirma { get; set; }
		bool PrintAclara { get; set; }
		bool PrintTelef { get; set; }
		bool PrintHeader { get; set; }
		bool PrintEstab { get; set; }
		DNFT_Tipo Tipo { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_DNFTarjeta 
		: MInput
		, IMI_DNFTarjeta_ClassInterface
	{
		public string LTipo { get; set; }
		public string LTarjeta { get; set; }
		public string LCliente { get; set; }
		public int LVencim { get; set; }
		public string LEstab { get; set; }
		public string LCupon { get; set; }
		public string LComprob { get; set; }
		public string LAutoriz { get; set; }
		public string LOperacion { get; set; }
		public decimal LImporte { get; set; }
		public int LCuotas { get; set; }
		public string LMoneda { get; set; }
		public string LTerminal { get; set; }
		public string LLote { get; set; }
		public string LTpv { get; set; }
		public string LSucu { get; set; }
		public string LOpe { get; set; }
		public string LReferen { get; set; }
		public string LLibre1 { get; set; }
		public string LLibre2 { get; set; }
		public string LLibre3 { get; set; }
		public string LLibre4 { get; set; }
		public string LLibre5 { get; set; }
		public string LLibre6 { get; set; }
		public int ReempColaNum1 { get; set; }
		public string ReempColaTexto1 { get; set; }
		public int ReempColaNum2 { get; set; }
		public string ReempColaTexto2 { get; set; }
		public int ReempColaNum3 { get; set; }
		public string ReempColaTexto3 { get; set; }
		public bool Cut { get; set; }
		public bool PrintDomi { get; set; }
		public bool PrintDoc { get; set; }
		public bool PrintFirma { get; set; }
		public bool PrintAclara { get; set; }
		public bool PrintTelef { get; set; }
		public bool PrintHeader { get; set; }
		public bool PrintEstab { get; set; }
		public DNFT_Tipo Tipo { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Cut) extension |= 0x01;
				if(PrintDomi) extension |= 0x08;
				if(PrintDoc) extension |= 0x10;
				if(PrintFirma) extension |= 0x20;
				if(PrintAclara) extension |= 0x40;
				if(PrintTelef) extension |= 0x80;
				if(PrintHeader) extension |= 0x400;
				if(PrintEstab) extension |= 0x800;
				extension |= ((((int) Tipo) & 0x0003) << 8);
				SetOpcode(0x0F01, extension, list);
				Append_RT(list, LTipo, -1, 0, true);
				Append_RT(list, LTarjeta, -1, 0, true);
				Append_RT(list, LCliente, -1, 0, true);
				Append_D(list, LVencim, 6, 0, true);
				Append_RT(list, LEstab, -1, 0, true);
				Append_RT(list, LCupon, -1, 0, false);
				Append_RT(list, LComprob, -1, 0, true);
				Append_RT(list, LAutoriz, -1, 0, true);
				Append_RT(list, LOperacion, -1, 0, true);
				Append_N(list, LImporte, 16, 2, true);
				Append_N(list, LCuotas, 4, 0, true);
				Append_RT(list, LMoneda, -1, 0, true);
				Append_RT(list, LTerminal, -1, 0, true);
				Append_RT(list, LLote, -1, 0, true);
				Append_RT(list, LTpv, -1, 0, true);
				Append_RT(list, LSucu, -1, 0, true);
				Append_RT(list, LOpe, -1, 0, true);
				Append_RT(list, LReferen, -1, 0, true);
				Append_RT(list, LLibre1, -1, 0, true);
				Append_RT(list, LLibre2, -1, 0, true);
				Append_RT(list, LLibre3, -1, 0, true);
				Append_RT(list, LLibre4, -1, 0, true);
				Append_RT(list, LLibre5, -1, 0, true);
				Append_RT(list, LLibre6, -1, 0, true);
				Append_N(list, ReempColaNum1, 3, 0, true);
				Append_RT(list, ReempColaTexto1, -1, 0, true);
				Append_N(list, ReempColaNum2, 3, 0, true);
				Append_RT(list, ReempColaTexto2, -1, 0, true);
				Append_N(list, ReempColaNum3, 3, 0, true);
				Append_RT(list, ReempColaTexto3, -1, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_DNFTarjeta_ClassInterface
	{
		int Numero { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_DNFTarjeta  
		: MOutput
		, IMO_DNFTarjeta_ClassInterface
	{
		public int Numero { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Numero = Extract_N(data, 5, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_DNFTarjeta_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_DNFTarjeta_ClassInterface Input { get; }
		IMO_DNFTarjeta_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_DNFTarjeta 
	    : CMD_Generic
		, ICMD_DNFTarjeta_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DNFTarjeta"; }}
		public override int Opcode { get { return 0x0F01; }}
		public override string Description { get { return "Realiza la impresión de un documento de respaldo de operaciones en tarjeta de crédito, débito o talones promocionales."; }}

		public IMI_DNFTarjeta_ClassInterface Input { get; protected set; }
		public IMO_DNFTarjeta_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_DNFTarjeta();
			Output = new MO_DNFTarjeta();
		}

		// Ctor
		public CMD_DNFTarjeta()
		{
			SetDefaults();
		}
	}

	public enum DNFT_Tipo 
	{
		TCredito = 0,	// 00
		TDebito = 1,	// 01
		TPromo = 2,	// 10
	};

}
