// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_DNFCobroServ.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_DNFCobroServ_ClassInterface
	{
		string LTitulo { get; set; }
		string LFecha { get; set; }
		string LStrMonto { get; set; }
		decimal Monto { get; set; }
		string LLibre1 { get; set; }
		string LLibre2 { get; set; }
		string LLibre3 { get; set; }
		string LLibre4 { get; set; }
		string LLibre5 { get; set; }
		string LLibre6 { get; set; }
		string LLibre7 { get; set; }
		string LLibre8 { get; set; }
		string LLibre9 { get; set; }
		int ReempColaNum1 { get; set; }
		string ReempColaTexto1 { get; set; }
		int ReempColaNum2 { get; set; }
		string ReempColaTexto2 { get; set; }
		int ReempColaNum3 { get; set; }
		string ReempColaTexto3 { get; set; }
		bool Cut { get; set; }
		bool PrintHeader { get; set; }
		bool PrintEstab { get; set; }
		DNFCS_Estacion Estacion { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_DNFCobroServ 
		: MInput
		, IMI_DNFCobroServ_ClassInterface
	{
		public string LTitulo { get; set; }
		public string LFecha { get; set; }
		public string LStrMonto { get; set; }
		public decimal Monto { get; set; }
		public string LLibre1 { get; set; }
		public string LLibre2 { get; set; }
		public string LLibre3 { get; set; }
		public string LLibre4 { get; set; }
		public string LLibre5 { get; set; }
		public string LLibre6 { get; set; }
		public string LLibre7 { get; set; }
		public string LLibre8 { get; set; }
		public string LLibre9 { get; set; }
		public int ReempColaNum1 { get; set; }
		public string ReempColaTexto1 { get; set; }
		public int ReempColaNum2 { get; set; }
		public string ReempColaTexto2 { get; set; }
		public int ReempColaNum3 { get; set; }
		public string ReempColaTexto3 { get; set; }
		public bool Cut { get; set; }
		public bool PrintHeader { get; set; }
		public bool PrintEstab { get; set; }
		public DNFCS_Estacion Estacion { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Cut) extension |= 0x04;
				if(PrintHeader) extension |= 0x400;
				if(PrintEstab) extension |= 0x800;
				extension |= (((int) Estacion) & 0x0003);
				SetOpcode(0x0F05, extension, list);
				Append_RT(list, LTitulo, -1, 0, true);
				Append_RT(list, LFecha, -1, 0, true);
				Append_RT(list, LStrMonto, -1, 0, true);
				Append_N(list, Monto, 13, 2, false);
				Append_RT(list, LLibre1, -1, 0, true);
				Append_RT(list, LLibre2, -1, 0, true);
				Append_RT(list, LLibre3, -1, 0, true);
				Append_RT(list, LLibre4, -1, 0, true);
				Append_RT(list, LLibre5, -1, 0, true);
				Append_RT(list, LLibre6, -1, 0, true);
				Append_RT(list, LLibre7, -1, 0, true);
				Append_RT(list, LLibre8, -1, 0, true);
				Append_RT(list, LLibre9, -1, 0, true);
				Append_N(list, ReempColaNum1, 3, 0, true);
				Append_RT(list, ReempColaTexto1, -1, 0, true);
				Append_N(list, ReempColaNum2, 3, 0, true);
				Append_RT(list, ReempColaTexto2, -1, 0, true);
				Append_N(list, ReempColaNum3, 3, 0, true);
				Append_RT(list, ReempColaTexto3, -1, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_DNFCobroServ_ClassInterface
	{
		int Numero { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_DNFCobroServ  
		: MOutput
		, IMO_DNFCobroServ_ClassInterface
	{
		public int Numero { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Numero = Extract_N(data, 5, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_DNFCobroServ_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_DNFCobroServ_ClassInterface Input { get; }
		IMO_DNFCobroServ_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_DNFCobroServ 
	    : CMD_Generic
		, ICMD_DNFCobroServ_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DNFCobroServ"; }}
		public override int Opcode { get { return 0x0F05; }}
		public override string Description { get { return "Realiza la impresión de un talón de cobro de servicios."; }}

		public IMI_DNFCobroServ_ClassInterface Input { get; protected set; }
		public IMO_DNFCobroServ_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_DNFCobroServ();
			Output = new MO_DNFCobroServ();
		}

		// Ctor
		public CMD_DNFCobroServ()
		{
			SetDefaults();
		}
	}

	public enum DNFCS_Estacion 
	{
		Rollo = 3,	// 11
	};

}
