// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CommandTable.cs - Access objects in COM through properties

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
 

	// Sistema
	public class CSistema
	{

		private CMD_ObtenerEstado fldObtenerEstado;
		public CMD_ObtenerEstado ObtenerEstado { get { return (fldObtenerEstado == null)? (fldObtenerEstado = new CMD_ObtenerEstado()): fldObtenerEstado; }}

		private CMD_ObtenerErrorInicio fldObtenerErrorInicio;
		public CMD_ObtenerErrorInicio ObtenerErrorInicio { get { return (fldObtenerErrorInicio == null)? (fldObtenerErrorInicio = new CMD_ObtenerErrorInicio()): fldObtenerErrorInicio; }}

		private CMD_ObtenerErrorInterno fldObtenerErrorInterno;
		public CMD_ObtenerErrorInterno ObtenerErrorInterno { get { return (fldObtenerErrorInterno == null)? (fldObtenerErrorInterno = new CMD_ObtenerErrorInterno()): fldObtenerErrorInterno; }}

		private CMD_ObtenerID fldObtenerID;
		public CMD_ObtenerID ObtenerID { get { return (fldObtenerID == null)? (fldObtenerID = new CMD_ObtenerID()): fldObtenerID; }}

		private CMD_ConfigurarVelocidad fldConfigurarVelocidad;
		public CMD_ConfigurarVelocidad ConfigurarVelocidad { get { return (fldConfigurarVelocidad == null)? (fldConfigurarVelocidad = new CMD_ConfigurarVelocidad()): fldConfigurarVelocidad; }}
	}
 

	// Diagnostico
	public class CDiagnostico
	{

		private CMD_DiagEquipo fldDiagEquipo;
		public CMD_DiagEquipo DiagEquipo { get { return (fldDiagEquipo == null)? (fldDiagEquipo = new CMD_DiagEquipo()): fldDiagEquipo; }}

		private CMD_RippleTest fldRippleTest;
		public CMD_RippleTest RippleTest { get { return (fldRippleTest == null)? (fldRippleTest = new CMD_RippleTest()): fldRippleTest; }}

		private CMD_ObtenerInfoEquipo fldObtenerInfoEquipo;
		public CMD_ObtenerInfoEquipo ObtenerInfoEquipo { get { return (fldObtenerInfoEquipo == null)? (fldObtenerInfoEquipo = new CMD_ObtenerInfoEquipo()): fldObtenerInfoEquipo; }}

		private CMD_ObtenerInfoMF fldObtenerInfoMF;
		public CMD_ObtenerInfoMF ObtenerInfoMF { get { return (fldObtenerInfoMF == null)? (fldObtenerInfoMF = new CMD_ObtenerInfoMF()): fldObtenerInfoMF; }}

		private CMD_TicketTecnico fldTicketTecnico;
		public CMD_TicketTecnico TicketTecnico { get { return (fldTicketTecnico == null)? (fldTicketTecnico = new CMD_TicketTecnico()): fldTicketTecnico; }}

		private CMD_ObtenerInfoCertif fldObtenerInfoCertif;
		public CMD_ObtenerInfoCertif ObtenerInfoCertif { get { return (fldObtenerInfoCertif == null)? (fldObtenerInfoCertif = new CMD_ObtenerInfoCertif()): fldObtenerInfoCertif; }}
	}
 

	// Configuracion
	public class CConfiguracion
	{

		private CMD_ConfigFechaHora fldConfigFechaHora;
		public CMD_ConfigFechaHora ConfigFechaHora { get { return (fldConfigFechaHora == null)? (fldConfigFechaHora = new CMD_ConfigFechaHora()): fldConfigFechaHora; }}

		private CMD_ObtenerFechaHora fldObtenerFechaHora;
		public CMD_ObtenerFechaHora ObtenerFechaHora { get { return (fldObtenerFechaHora == null)? (fldObtenerFechaHora = new CMD_ObtenerFechaHora()): fldObtenerFechaHora; }}

		private CMD_ConfigRespIVA fldConfigRespIVA;
		public CMD_ConfigRespIVA ConfigRespIVA { get { return (fldConfigRespIVA == null)? (fldConfigRespIVA = new CMD_ConfigRespIVA()): fldConfigRespIVA; }}

		private CMD_CambiarConfigAFIP fldCambiarConfigAFIP;
		public CMD_CambiarConfigAFIP CambiarConfigAFIP { get { return (fldCambiarConfigAFIP == null)? (fldCambiarConfigAFIP = new CMD_CambiarConfigAFIP()): fldCambiarConfigAFIP; }}

		private CMD_ObtenerConfigAFIP fldObtenerConfigAFIP;
		public CMD_ObtenerConfigAFIP ObtenerConfigAFIP { get { return (fldObtenerConfigAFIP == null)? (fldObtenerConfigAFIP = new CMD_ObtenerConfigAFIP()): fldObtenerConfigAFIP; }}

		private CMD_ObtenerDatosFiscalizacion fldObtenerDatosFiscalizacion;
		public CMD_ObtenerDatosFiscalizacion ObtenerDatosFiscalizacion { get { return (fldObtenerDatosFiscalizacion == null)? (fldObtenerDatosFiscalizacion = new CMD_ObtenerDatosFiscalizacion()): fldObtenerDatosFiscalizacion; }}

		private CMD_ConfigEncabezado fldConfigEncabezado;
		public CMD_ConfigEncabezado ConfigEncabezado { get { return (fldConfigEncabezado == null)? (fldConfigEncabezado = new CMD_ConfigEncabezado()): fldConfigEncabezado; }}

		private CMD_ObtenerEncabezado fldObtenerEncabezado;
		public CMD_ObtenerEncabezado ObtenerEncabezado { get { return (fldObtenerEncabezado == null)? (fldObtenerEncabezado = new CMD_ObtenerEncabezado()): fldObtenerEncabezado; }}

		private CMD_ConfigCola fldConfigCola;
		public CMD_ConfigCola ConfigCola { get { return (fldConfigCola == null)? (fldConfigCola = new CMD_ConfigCola()): fldConfigCola; }}

		private CMD_ObtenerCola fldObtenerCola;
		public CMD_ObtenerCola ObtenerCola { get { return (fldObtenerCola == null)? (fldObtenerCola = new CMD_ObtenerCola()): fldObtenerCola; }}

		private CMD_ConfigInfoEstab fldConfigInfoEstab;
		public CMD_ConfigInfoEstab ConfigInfoEstab { get { return (fldConfigInfoEstab == null)? (fldConfigInfoEstab = new CMD_ConfigInfoEstab()): fldConfigInfoEstab; }}

		private CMD_ObtenerInfoEstab fldObtenerInfoEstab;
		public CMD_ObtenerInfoEstab ObtenerInfoEstab { get { return (fldObtenerInfoEstab == null)? (fldObtenerInfoEstab = new CMD_ObtenerInfoEstab()): fldObtenerInfoEstab; }}

		private CMD_ObtenerConfigClaves fldObtenerConfigClaves;
		public CMD_ObtenerConfigClaves ObtenerConfigClaves { get { return (fldObtenerConfigClaves == null)? (fldObtenerConfigClaves = new CMD_ObtenerConfigClaves()): fldObtenerConfigClaves; }}

		private CMD_LogoIniciarCarga fldLogoIniciarCarga;
		public CMD_LogoIniciarCarga LogoIniciarCarga { get { return (fldLogoIniciarCarga == null)? (fldLogoIniciarCarga = new CMD_LogoIniciarCarga()): fldLogoIniciarCarga; }}

		private CMD_LogoContenido fldLogoContenido;
		public CMD_LogoContenido LogoContenido { get { return (fldLogoContenido == null)? (fldLogoContenido = new CMD_LogoContenido()): fldLogoContenido; }}

		private CMD_LogoFinalizarCarga fldLogoFinalizarCarga;
		public CMD_LogoFinalizarCarga LogoFinalizarCarga { get { return (fldLogoFinalizarCarga == null)? (fldLogoFinalizarCarga = new CMD_LogoFinalizarCarga()): fldLogoFinalizarCarga; }}

		private CMD_LogoCancelarCarga fldLogoCancelarCarga;
		public CMD_LogoCancelarCarga LogoCancelarCarga { get { return (fldLogoCancelarCarga == null)? (fldLogoCancelarCarga = new CMD_LogoCancelarCarga()): fldLogoCancelarCarga; }}

		private CMD_LogoEliminar fldLogoEliminar;
		public CMD_LogoEliminar LogoEliminar { get { return (fldLogoEliminar == null)? (fldLogoEliminar = new CMD_LogoEliminar()): fldLogoEliminar; }}

		private CMD_ActivaImpresionArqueo fldActivaImpresionArqueo;
		public CMD_ActivaImpresionArqueo ActivaImpresionArqueo { get { return (fldActivaImpresionArqueo == null)? (fldActivaImpresionArqueo = new CMD_ActivaImpresionArqueo()): fldActivaImpresionArqueo; }}

		private CMD_ObtenerImpresionArqueo fldObtenerImpresionArqueo;
		public CMD_ObtenerImpresionArqueo ObtenerImpresionArqueo { get { return (fldObtenerImpresionArqueo == null)? (fldObtenerImpresionArqueo = new CMD_ObtenerImpresionArqueo()): fldObtenerImpresionArqueo; }}

		private CMD_ResetFabrica fldResetFabrica;
		public CMD_ResetFabrica ResetFabrica { get { return (fldResetFabrica == null)? (fldResetFabrica = new CMD_ResetFabrica()): fldResetFabrica; }}

		private CMD_ConfigRedEstablece fldConfigRedEstablece;
		public CMD_ConfigRedEstablece ConfigRedEstablece { get { return (fldConfigRedEstablece == null)? (fldConfigRedEstablece = new CMD_ConfigRedEstablece()): fldConfigRedEstablece; }}

		private CMD_ConfigRedLee fldConfigRedLee;
		public CMD_ConfigRedLee ConfigRedLee { get { return (fldConfigRedLee == null)? (fldConfigRedLee = new CMD_ConfigRedLee()): fldConfigRedLee; }}

		private CMD_DisplayConfig fldDisplayConfig;
		public CMD_DisplayConfig DisplayConfig { get { return (fldDisplayConfig == null)? (fldDisplayConfig = new CMD_DisplayConfig()): fldDisplayConfig; }}
	}
 

	// Impresora
	public class CImpresora
	{

		private CMD_AvanzarPapel fldAvanzarPapel;
		public CMD_AvanzarPapel AvanzarPapel { get { return (fldAvanzarPapel == null)? (fldAvanzarPapel = new CMD_AvanzarPapel()): fldAvanzarPapel; }}

		private CMD_CortarPapel fldCortarPapel;
		public CMD_CortarPapel CortarPapel { get { return (fldCortarPapel == null)? (fldCortarPapel = new CMD_CortarPapel()): fldCortarPapel; }}

		private CMD_AbrirGaveta fldAbrirGaveta;
		public CMD_AbrirGaveta AbrirGaveta { get { return (fldAbrirGaveta == null)? (fldAbrirGaveta = new CMD_AbrirGaveta()): fldAbrirGaveta; }}

		private CMD_ConfigCuchilla fldConfigCuchilla;
		public CMD_ConfigCuchilla ConfigCuchilla { get { return (fldConfigCuchilla == null)? (fldConfigCuchilla = new CMD_ConfigCuchilla()): fldConfigCuchilla; }}

		private CMD_ObtenerConfigCuchilla fldObtenerConfigCuchilla;
		public CMD_ObtenerConfigCuchilla ObtenerConfigCuchilla { get { return (fldObtenerConfigCuchilla == null)? (fldObtenerConfigCuchilla = new CMD_ObtenerConfigCuchilla()): fldObtenerConfigCuchilla; }}

		private CMD_ConfigurarFuente fldConfigurarFuente;
		public CMD_ConfigurarFuente ConfigurarFuente { get { return (fldConfigurarFuente == null)? (fldConfigurarFuente = new CMD_ConfigurarFuente()): fldConfigurarFuente; }}

		private CMD_ObtenerFuente fldObtenerFuente;
		public CMD_ObtenerFuente ObtenerFuente { get { return (fldObtenerFuente == null)? (fldObtenerFuente = new CMD_ObtenerFuente()): fldObtenerFuente; }}

		private CMD_ConfigurarDensidadImpresion fldConfigurarDensidadImpresion;
		public CMD_ConfigurarDensidadImpresion ConfigurarDensidadImpresion { get { return (fldConfigurarDensidadImpresion == null)? (fldConfigurarDensidadImpresion = new CMD_ConfigurarDensidadImpresion()): fldConfigurarDensidadImpresion; }}

		private CMD_ObtenerDensidadImpresion fldObtenerDensidadImpresion;
		public CMD_ObtenerDensidadImpresion ObtenerDensidadImpresion { get { return (fldObtenerDensidadImpresion == null)? (fldObtenerDensidadImpresion = new CMD_ObtenerDensidadImpresion()): fldObtenerDensidadImpresion; }}
	}
 

	// Jornada Fiscal
	public class CJornadaFiscal
	{

		private CMD_JORZeta fldJORZeta;
		public CMD_JORZeta JORZeta { get { return (fldJORZeta == null)? (fldJORZeta = new CMD_JORZeta()): fldJORZeta; }}

		private CMD_JORTotalVentas fldJORTotalVentas;
		public CMD_JORTotalVentas JORTotalVentas { get { return (fldJORTotalVentas == null)? (fldJORTotalVentas = new CMD_JORTotalVentas()): fldJORTotalVentas; }}

		private CMD_JORGetInfoVentasJornada fldJORGetInfoVentasJornada;
		public CMD_JORGetInfoVentasJornada JORGetInfoVentasJornada { get { return (fldJORGetInfoVentasJornada == null)? (fldJORGetInfoVentasJornada = new CMD_JORGetInfoVentasJornada()): fldJORGetInfoVentasJornada; }}

		private CMD_JORGetInfoImpuestosJornada fldJORGetInfoImpuestosJornada;
		public CMD_JORGetInfoImpuestosJornada JORGetInfoImpuestosJornada { get { return (fldJORGetInfoImpuestosJornada == null)? (fldJORGetInfoImpuestosJornada = new CMD_JORGetInfoImpuestosJornada()): fldJORGetInfoImpuestosJornada; }}

		private CMD_JORGetInfoOtrosTributosJornada fldJORGetInfoOtrosTributosJornada;
		public CMD_JORGetInfoOtrosTributosJornada JORGetInfoOtrosTributosJornada { get { return (fldJORGetInfoOtrosTributosJornada == null)? (fldJORGetInfoOtrosTributosJornada = new CMD_JORGetInfoOtrosTributosJornada()): fldJORGetInfoOtrosTributosJornada; }}

		private CMD_JORAudRangoFecha fldJORAudRangoFecha;
		public CMD_JORAudRangoFecha JORAudRangoFecha { get { return (fldJORAudRangoFecha == null)? (fldJORAudRangoFecha = new CMD_JORAudRangoFecha()): fldJORAudRangoFecha; }}

		private CMD_JORAudRangoZetas fldJORAudRangoZetas;
		public CMD_JORAudRangoZetas JORAudRangoZetas { get { return (fldJORAudRangoZetas == null)? (fldJORAudRangoZetas = new CMD_JORAudRangoZetas()): fldJORAudRangoZetas; }}

		private CMD_JORAudEnumera fldJORAudEnumera;
		public CMD_JORAudEnumera JORAudEnumera { get { return (fldJORAudEnumera == null)? (fldJORAudEnumera = new CMD_JORAudEnumera()): fldJORAudEnumera; }}

		private CMD_JORAudFinal fldJORAudFinal;
		public CMD_JORAudFinal JORAudFinal { get { return (fldJORAudFinal == null)? (fldJORAudFinal = new CMD_JORAudFinal()): fldJORAudFinal; }}

		private CMD_JORAudCancela fldJORAudCancela;
		public CMD_JORAudCancela JORAudCancela { get { return (fldJORAudCancela == null)? (fldJORAudCancela = new CMD_JORAudCancela()): fldJORAudCancela; }}

		private CMD_JORGetInfoContadoresJornada fldJORGetInfoContadoresJornada;
		public CMD_JORGetInfoContadoresJornada JORGetInfoContadoresJornada { get { return (fldJORGetInfoContadoresJornada == null)? (fldJORGetInfoContadoresJornada = new CMD_JORGetInfoContadoresJornada()): fldJORGetInfoContadoresJornada; }}

		private CMD_JORDupliInicia fldJORDupliInicia;
		public CMD_JORDupliInicia JORDupliInicia { get { return (fldJORDupliInicia == null)? (fldJORDupliInicia = new CMD_JORDupliInicia()): fldJORDupliInicia; }}

		private CMD_JORDupliEnumera fldJORDupliEnumera;
		public CMD_JORDupliEnumera JORDupliEnumera { get { return (fldJORDupliEnumera == null)? (fldJORDupliEnumera = new CMD_JORDupliEnumera()): fldJORDupliEnumera; }}

		private CMD_JORDupliFinal fldJORDupliFinal;
		public CMD_JORDupliFinal JORDupliFinal { get { return (fldJORDupliFinal == null)? (fldJORDupliFinal = new CMD_JORDupliFinal()): fldJORDupliFinal; }}

		private CMD_JORDupliCancela fldJORDupliCancela;
		public CMD_JORDupliCancela JORDupliCancela { get { return (fldJORDupliCancela == null)? (fldJORDupliCancela = new CMD_JORDupliCancela()): fldJORDupliCancela; }}
	}
 

	// Descarga
	public class CDescarga
	{

		private CMD_DNL_Borra fldDNLBorra;
		public CMD_DNL_Borra DNLBorra { get { return (fldDNLBorra == null)? (fldDNLBorra = new CMD_DNL_Borra()): fldDNLBorra; }}

		private CMD_DNL_Info fldDNLInfo;
		public CMD_DNL_Info DNLInfo { get { return (fldDNLInfo == null)? (fldDNLInfo = new CMD_DNL_Info()): fldDNLInfo; }}

		private CMD_DNL_RangoFechas fldDNLRangoFechas;
		public CMD_DNL_RangoFechas DNLRangoFechas { get { return (fldDNLRangoFechas == null)? (fldDNLRangoFechas = new CMD_DNL_RangoFechas()): fldDNLRangoFechas; }}

		private CMD_DNL_RangoZetas fldDNLRangoZetas;
		public CMD_DNL_RangoZetas DNLRangoZetas { get { return (fldDNLRangoZetas == null)? (fldDNLRangoZetas = new CMD_DNL_RangoZetas()): fldDNLRangoZetas; }}

		private CMD_DNL_IvaVentas fldDNLIvaVentas;
		public CMD_DNL_IvaVentas DNLIvaVentas { get { return (fldDNLIvaVentas == null)? (fldDNLIvaVentas = new CMD_DNL_IvaVentas()): fldDNLIvaVentas; }}

		private CMD_DNL_MemoriaFiscal fldDNLMemoriaFiscal;
		public CMD_DNL_MemoriaFiscal DNLMemoriaFiscal { get { return (fldDNLMemoriaFiscal == null)? (fldDNLMemoriaFiscal = new CMD_DNL_MemoriaFiscal()): fldDNLMemoriaFiscal; }}

		private CMD_DNL_Monitor fldDNLMonitor;
		public CMD_DNL_Monitor DNLMonitor { get { return (fldDNLMonitor == null)? (fldDNLMonitor = new CMD_DNL_Monitor()): fldDNLMonitor; }}

		private CMD_DNL_Enumera fldDNLEnumera;
		public CMD_DNL_Enumera DNLEnumera { get { return (fldDNLEnumera == null)? (fldDNLEnumera = new CMD_DNL_Enumera()): fldDNLEnumera; }}

		private CMD_DNL_Final fldDNLFinal;
		public CMD_DNL_Final DNLFinal { get { return (fldDNLFinal == null)? (fldDNLFinal = new CMD_DNL_Final()): fldDNLFinal; }}

		private CMD_DNL_Cancela fldDNLCancela;
		public CMD_DNL_Cancela DNLCancela { get { return (fldDNLCancela == null)? (fldDNLCancela = new CMD_DNL_Cancela()): fldDNLCancela; }}
	}
 

	// Ticket
	public class CTicket
	{

		private CMD_TKAbrir fldTKAbrir;
		public CMD_TKAbrir TKAbrir { get { return (fldTKAbrir == null)? (fldTKAbrir = new CMD_TKAbrir()): fldTKAbrir; }}

		private CMD_TKItem fldTKItem;
		public CMD_TKItem TKItem { get { return (fldTKItem == null)? (fldTKItem = new CMD_TKItem()): fldTKItem; }}

		private CMD_TKSubtotal fldTKSubtotal;
		public CMD_TKSubtotal TKSubtotal { get { return (fldTKSubtotal == null)? (fldTKSubtotal = new CMD_TKSubtotal()): fldTKSubtotal; }}

		private CMD_TKDescuento fldTKDescuento;
		public CMD_TKDescuento TKDescuento { get { return (fldTKDescuento == null)? (fldTKDescuento = new CMD_TKDescuento()): fldTKDescuento; }}

		private CMD_TKPago fldTKPago;
		public CMD_TKPago TKPago { get { return (fldTKPago == null)? (fldTKPago = new CMD_TKPago()): fldTKPago; }}

		private CMD_TKCerrar fldTKCerrar;
		public CMD_TKCerrar TKCerrar { get { return (fldTKCerrar == null)? (fldTKCerrar = new CMD_TKCerrar()): fldTKCerrar; }}

		private CMD_TKAnula fldTKAnula;
		public CMD_TKAnula TKAnula { get { return (fldTKAnula == null)? (fldTKAnula = new CMD_TKAnula()): fldTKAnula; }}

		private CMD_TKSetConfig fldTKSetConfig;
		public CMD_TKSetConfig TKSetConfig { get { return (fldTKSetConfig == null)? (fldTKSetConfig = new CMD_TKSetConfig()): fldTKSetConfig; }}

		private CMD_TKGetConfig fldTKGetConfig;
		public CMD_TKGetConfig TKGetConfig { get { return (fldTKGetConfig == null)? (fldTKGetConfig = new CMD_TKGetConfig()): fldTKGetConfig; }}

		private CMD_TKGetInfo fldTKGetInfo;
		public CMD_TKGetInfo TKGetInfo { get { return (fldTKGetInfo == null)? (fldTKGetInfo = new CMD_TKGetInfo()): fldTKGetInfo; }}

		private CMD_TKGetIVA fldTKGetIVA;
		public CMD_TKGetIVA TKGetIVA { get { return (fldTKGetIVA == null)? (fldTKGetIVA = new CMD_TKGetIVA()): fldTKGetIVA; }}

		private CMD_TKGetPago fldTKGetPago;
		public CMD_TKGetPago TKGetPago { get { return (fldTKGetPago == null)? (fldTKGetPago = new CMD_TKGetPago()): fldTKGetPago; }}

		private CMD_TKGetVentas fldTKGetVentas;
		public CMD_TKGetVentas TKGetVentas { get { return (fldTKGetVentas == null)? (fldTKGetVentas = new CMD_TKGetVentas()): fldTKGetVentas; }}

		private CMD_TKGetImpInt fldTKGetImpInt;
		public CMD_TKGetImpInt TKGetImpInt { get { return (fldTKGetImpInt == null)? (fldTKGetImpInt = new CMD_TKGetImpInt()): fldTKGetImpInt; }}

		private CMD_TKGetOtrosTrib fldTKGetOtrosTrib;
		public CMD_TKGetOtrosTrib TKGetOtrosTrib { get { return (fldTKGetOtrosTrib == null)? (fldTKGetOtrosTrib = new CMD_TKGetOtrosTrib()): fldTKGetOtrosTrib; }}

		private CMD_TKGetUltimoCierre fldTKGetUltimoCierre;
		public CMD_TKGetUltimoCierre TKGetUltimoCierre { get { return (fldTKGetUltimoCierre == null)? (fldTKGetUltimoCierre = new CMD_TKGetUltimoCierre()): fldTKGetUltimoCierre; }}

		private CMD_TKOtroTributo fldTKOtroTributo;
		public CMD_TKOtroTributo TKOtroTributo { get { return (fldTKOtroTributo == null)? (fldTKOtroTributo = new CMD_TKOtroTributo()): fldTKOtroTributo; }}

		private CMD_TKSubtotal2 fldTKSubtotal2;
		public CMD_TKSubtotal2 TKSubtotal2 { get { return (fldTKSubtotal2 == null)? (fldTKSubtotal2 = new CMD_TKSubtotal2()): fldTKSubtotal2; }}

		private CMD_TKUnitario fldTKUnitario;
		public CMD_TKUnitario TKUnitario { get { return (fldTKUnitario == null)? (fldTKUnitario = new CMD_TKUnitario()): fldTKUnitario; }}
	}
 

	// Ticket Factura
	public class CTicketFactura
	{

		private CMD_TFAbrir fldTFAbrir;
		public CMD_TFAbrir TFAbrir { get { return (fldTFAbrir == null)? (fldTFAbrir = new CMD_TFAbrir()): fldTFAbrir; }}

		private CMD_TFItem fldTFItem;
		public CMD_TFItem TFItem { get { return (fldTFItem == null)? (fldTFItem = new CMD_TFItem()): fldTFItem; }}

		private CMD_TFSubtotal fldTFSubtotal;
		public CMD_TFSubtotal TFSubtotal { get { return (fldTFSubtotal == null)? (fldTFSubtotal = new CMD_TFSubtotal()): fldTFSubtotal; }}

		private CMD_TFDescuento fldTFDescuento;
		public CMD_TFDescuento TFDescuento { get { return (fldTFDescuento == null)? (fldTFDescuento = new CMD_TFDescuento()): fldTFDescuento; }}

		private CMD_TFPago fldTFPago;
		public CMD_TFPago TFPago { get { return (fldTFPago == null)? (fldTFPago = new CMD_TFPago()): fldTFPago; }}

		private CMD_TFCerrar fldTFCerrar;
		public CMD_TFCerrar TFCerrar { get { return (fldTFCerrar == null)? (fldTFCerrar = new CMD_TFCerrar()): fldTFCerrar; }}

		private CMD_TFAnula fldTFAnula;
		public CMD_TFAnula TFAnula { get { return (fldTFAnula == null)? (fldTFAnula = new CMD_TFAnula()): fldTFAnula; }}

		private CMD_TFSetConfig fldTFSetConfig;
		public CMD_TFSetConfig TFSetConfig { get { return (fldTFSetConfig == null)? (fldTFSetConfig = new CMD_TFSetConfig()): fldTFSetConfig; }}

		private CMD_TFGetConfig fldTFGetConfig;
		public CMD_TFGetConfig TFGetConfig { get { return (fldTFGetConfig == null)? (fldTFGetConfig = new CMD_TFGetConfig()): fldTFGetConfig; }}

		private CMD_TFGetInfo fldTFGetInfo;
		public CMD_TFGetInfo TFGetInfo { get { return (fldTFGetInfo == null)? (fldTFGetInfo = new CMD_TFGetInfo()): fldTFGetInfo; }}

		private CMD_TFGetIVA fldTFGetIVA;
		public CMD_TFGetIVA TFGetIVA { get { return (fldTFGetIVA == null)? (fldTFGetIVA = new CMD_TFGetIVA()): fldTFGetIVA; }}

		private CMD_TFGetPago fldTFGetPago;
		public CMD_TFGetPago TFGetPago { get { return (fldTFGetPago == null)? (fldTFGetPago = new CMD_TFGetPago()): fldTFGetPago; }}

		private CMD_TFGetVentas fldTFGetVentas;
		public CMD_TFGetVentas TFGetVentas { get { return (fldTFGetVentas == null)? (fldTFGetVentas = new CMD_TFGetVentas()): fldTFGetVentas; }}

		private CMD_TFGetImpInt fldTFGetImpInt;
		public CMD_TFGetImpInt TFGetImpInt { get { return (fldTFGetImpInt == null)? (fldTFGetImpInt = new CMD_TFGetImpInt()): fldTFGetImpInt; }}

		private CMD_TFGetOtrosTrib fldTFGetOtrosTrib;
		public CMD_TFGetOtrosTrib TFGetOtrosTrib { get { return (fldTFGetOtrosTrib == null)? (fldTFGetOtrosTrib = new CMD_TFGetOtrosTrib()): fldTFGetOtrosTrib; }}

		private CMD_TFGetUltimoCierre fldTFGetUltimoCierre;
		public CMD_TFGetUltimoCierre TFGetUltimoCierre { get { return (fldTFGetUltimoCierre == null)? (fldTFGetUltimoCierre = new CMD_TFGetUltimoCierre()): fldTFGetUltimoCierre; }}

		private CMD_TFOtroTributo fldTFOtroTributo;
		public CMD_TFOtroTributo TFOtroTributo { get { return (fldTFOtroTributo == null)? (fldTFOtroTributo = new CMD_TFOtroTributo()): fldTFOtroTributo; }}

		private CMD_TFSubtotal2 fldTFSubtotal2;
		public CMD_TFSubtotal2 TFSubtotal2 { get { return (fldTFSubtotal2 == null)? (fldTFSubtotal2 = new CMD_TFSubtotal2()): fldTFSubtotal2; }}
	}
 

	// Nota de Credito
	public class CNotaDeCredito
	{

		private CMD_NCAbrir fldNCAbrir;
		public CMD_NCAbrir NCAbrir { get { return (fldNCAbrir == null)? (fldNCAbrir = new CMD_NCAbrir()): fldNCAbrir; }}

		private CMD_NCItem fldNCItem;
		public CMD_NCItem NCItem { get { return (fldNCItem == null)? (fldNCItem = new CMD_NCItem()): fldNCItem; }}

		private CMD_NCSubtotal fldNCSubtotal;
		public CMD_NCSubtotal NCSubtotal { get { return (fldNCSubtotal == null)? (fldNCSubtotal = new CMD_NCSubtotal()): fldNCSubtotal; }}

		private CMD_NCDescuento fldNCDescuento;
		public CMD_NCDescuento NCDescuento { get { return (fldNCDescuento == null)? (fldNCDescuento = new CMD_NCDescuento()): fldNCDescuento; }}

		private CMD_NCPago fldNCPago;
		public CMD_NCPago NCPago { get { return (fldNCPago == null)? (fldNCPago = new CMD_NCPago()): fldNCPago; }}

		private CMD_NCCerrar fldNCCerrar;
		public CMD_NCCerrar NCCerrar { get { return (fldNCCerrar == null)? (fldNCCerrar = new CMD_NCCerrar()): fldNCCerrar; }}

		private CMD_NCAnula fldNCAnula;
		public CMD_NCAnula NCAnula { get { return (fldNCAnula == null)? (fldNCAnula = new CMD_NCAnula()): fldNCAnula; }}

		private CMD_NCSetConfig fldNCSetConfig;
		public CMD_NCSetConfig NCSetConfig { get { return (fldNCSetConfig == null)? (fldNCSetConfig = new CMD_NCSetConfig()): fldNCSetConfig; }}

		private CMD_NCGetConfig fldNCGetConfig;
		public CMD_NCGetConfig NCGetConfig { get { return (fldNCGetConfig == null)? (fldNCGetConfig = new CMD_NCGetConfig()): fldNCGetConfig; }}

		private CMD_NCGetInfo fldNCGetInfo;
		public CMD_NCGetInfo NCGetInfo { get { return (fldNCGetInfo == null)? (fldNCGetInfo = new CMD_NCGetInfo()): fldNCGetInfo; }}

		private CMD_NCGetIVA fldNCGetIVA;
		public CMD_NCGetIVA NCGetIVA { get { return (fldNCGetIVA == null)? (fldNCGetIVA = new CMD_NCGetIVA()): fldNCGetIVA; }}

		private CMD_NCGetPago fldNCGetPago;
		public CMD_NCGetPago NCGetPago { get { return (fldNCGetPago == null)? (fldNCGetPago = new CMD_NCGetPago()): fldNCGetPago; }}

		private CMD_NCGetVentas fldNCGetVentas;
		public CMD_NCGetVentas NCGetVentas { get { return (fldNCGetVentas == null)? (fldNCGetVentas = new CMD_NCGetVentas()): fldNCGetVentas; }}

		private CMD_NCGetImpInt fldNCGetImpInt;
		public CMD_NCGetImpInt NCGetImpInt { get { return (fldNCGetImpInt == null)? (fldNCGetImpInt = new CMD_NCGetImpInt()): fldNCGetImpInt; }}

		private CMD_NCGetOtrosTrib fldNCGetOtrosTrib;
		public CMD_NCGetOtrosTrib NCGetOtrosTrib { get { return (fldNCGetOtrosTrib == null)? (fldNCGetOtrosTrib = new CMD_NCGetOtrosTrib()): fldNCGetOtrosTrib; }}

		private CMD_NCGetUltimoCierre fldNCGetUltimoCierre;
		public CMD_NCGetUltimoCierre NCGetUltimoCierre { get { return (fldNCGetUltimoCierre == null)? (fldNCGetUltimoCierre = new CMD_NCGetUltimoCierre()): fldNCGetUltimoCierre; }}

		private CMD_NCOtroTributo fldNCOtroTributo;
		public CMD_NCOtroTributo NCOtroTributo { get { return (fldNCOtroTributo == null)? (fldNCOtroTributo = new CMD_NCOtroTributo()): fldNCOtroTributo; }}

		private CMD_NCSubtotal2 fldNCSubtotal2;
		public CMD_NCSubtotal2 NCSubtotal2 { get { return (fldNCSubtotal2 == null)? (fldNCSubtotal2 = new CMD_NCSubtotal2()): fldNCSubtotal2; }}
	}
 

	// DNFH Genericos
	public class CDNFHGenericos
	{

		private CMD_DNFH1Abrir fldDNFH1Abrir;
		public CMD_DNFH1Abrir DNFH1Abrir { get { return (fldDNFH1Abrir == null)? (fldDNFH1Abrir = new CMD_DNFH1Abrir()): fldDNFH1Abrir; }}

		private CMD_DNFH1Texto fldDNFH1Texto;
		public CMD_DNFH1Texto DNFH1Texto { get { return (fldDNFH1Texto == null)? (fldDNFH1Texto = new CMD_DNFH1Texto()): fldDNFH1Texto; }}

		private CMD_DNFH1Lineas fldDNFH1Lineas;
		public CMD_DNFH1Lineas DNFH1Lineas { get { return (fldDNFH1Lineas == null)? (fldDNFH1Lineas = new CMD_DNFH1Lineas()): fldDNFH1Lineas; }}

		private CMD_DNFH1Cerrar fldDNFH1Cerrar;
		public CMD_DNFH1Cerrar DNFH1Cerrar { get { return (fldDNFH1Cerrar == null)? (fldDNFH1Cerrar = new CMD_DNFH1Cerrar()): fldDNFH1Cerrar; }}

		private CMD_DNFH1CambiaPreferencias fldDNFH1CambiaPreferencias;
		public CMD_DNFH1CambiaPreferencias DNFH1CambiaPreferencias { get { return (fldDNFH1CambiaPreferencias == null)? (fldDNFH1CambiaPreferencias = new CMD_DNFH1CambiaPreferencias()): fldDNFH1CambiaPreferencias; }}

		private CMD_DNFH1ObtienePreferencias fldDNFH1ObtienePreferencias;
		public CMD_DNFH1ObtienePreferencias DNFH1ObtienePreferencias { get { return (fldDNFH1ObtienePreferencias == null)? (fldDNFH1ObtienePreferencias = new CMD_DNFH1ObtienePreferencias()): fldDNFH1ObtienePreferencias; }}

		private CMD_DNFH1Info fldDNFH1Info;
		public CMD_DNFH1Info DNFH1Info { get { return (fldDNFH1Info == null)? (fldDNFH1Info = new CMD_DNFH1Info()): fldDNFH1Info; }}

		private CMD_DNFH1Completo fldDNFH1Completo;
		public CMD_DNFH1Completo DNFH1Completo { get { return (fldDNFH1Completo == null)? (fldDNFH1Completo = new CMD_DNFH1Completo()): fldDNFH1Completo; }}

		private CMD_MensajeSistema fldMensajeSistema;
		public CMD_MensajeSistema MensajeSistema { get { return (fldMensajeSistema == null)? (fldMensajeSistema = new CMD_MensajeSistema()): fldMensajeSistema; }}
	}
 

	// DNF Autorizados
	public class CDNFAutorizados
	{

		private CMD_DNFTarjeta fldDNFTarjeta;
		public CMD_DNFTarjeta DNFTarjeta { get { return (fldDNFTarjeta == null)? (fldDNFTarjeta = new CMD_DNFTarjeta()): fldDNFTarjeta; }}

		private CMD_DNFFarmacia fldDNFFarmacia;
		public CMD_DNFFarmacia DNFFarmacia { get { return (fldDNFFarmacia == null)? (fldDNFFarmacia = new CMD_DNFFarmacia()): fldDNFFarmacia; }}

		private CMD_DNFEstacion fldDNFEstacion;
		public CMD_DNFEstacion DNFEstacion { get { return (fldDNFEstacion == null)? (fldDNFEstacion = new CMD_DNFEstacion()): fldDNFEstacion; }}

		private CMD_DNFReparto fldDNFReparto;
		public CMD_DNFReparto DNFReparto { get { return (fldDNFReparto == null)? (fldDNFReparto = new CMD_DNFReparto()): fldDNFReparto; }}

		private CMD_DNFCobroServ fldDNFCobroServ;
		public CMD_DNFCobroServ DNFCobroServ { get { return (fldDNFCobroServ == null)? (fldDNFCobroServ = new CMD_DNFCobroServ()): fldDNFCobroServ; }}

		private CMD_DNFRetiDota fldDNFRetiDota;
		public CMD_DNFRetiDota DNFRetiDota { get { return (fldDNFRetiDota == null)? (fldDNFRetiDota = new CMD_DNFRetiDota()): fldDNFRetiDota; }}

		private CMD_DNFCambio fldDNFCambio;
		public CMD_DNFCambio DNFCambio { get { return (fldDNFCambio == null)? (fldDNFCambio = new CMD_DNFCambio()): fldDNFCambio; }}

		private CMD_DNFCtaCte fldDNFCtaCte;
		public CMD_DNFCtaCte DNFCtaCte { get { return (fldDNFCtaCte == null)? (fldDNFCtaCte = new CMD_DNFCtaCte()): fldDNFCtaCte; }}
	}
 

	// DNFH Homologados
	public class CDNFHHomologados
	{

		private CMD_DNFHAbrir fldDNFHAbrir;
		public CMD_DNFHAbrir DNFHAbrir { get { return (fldDNFHAbrir == null)? (fldDNFHAbrir = new CMD_DNFHAbrir()): fldDNFHAbrir; }}

		private CMD_DNFHItem fldDNFHItem;
		public CMD_DNFHItem DNFHItem { get { return (fldDNFHItem == null)? (fldDNFHItem = new CMD_DNFHItem()): fldDNFHItem; }}

		private CMD_DNFHSubtotal fldDNFHSubtotal;
		public CMD_DNFHSubtotal DNFHSubtotal { get { return (fldDNFHSubtotal == null)? (fldDNFHSubtotal = new CMD_DNFHSubtotal()): fldDNFHSubtotal; }}

		private CMD_DNFHDescuento fldDNFHDescuento;
		public CMD_DNFHDescuento DNFHDescuento { get { return (fldDNFHDescuento == null)? (fldDNFHDescuento = new CMD_DNFHDescuento()): fldDNFHDescuento; }}

		private CMD_DNFHPago fldDNFHPago;
		public CMD_DNFHPago DNFHPago { get { return (fldDNFHPago == null)? (fldDNFHPago = new CMD_DNFHPago()): fldDNFHPago; }}

		private CMD_DFNHCerrar fldDFNHCerrar;
		public CMD_DFNHCerrar DFNHCerrar { get { return (fldDFNHCerrar == null)? (fldDFNHCerrar = new CMD_DFNHCerrar()): fldDFNHCerrar; }}

		private CMD_DNFHAnula fldDNFHAnula;
		public CMD_DNFHAnula DNFHAnula { get { return (fldDNFHAnula == null)? (fldDNFHAnula = new CMD_DNFHAnula()): fldDNFHAnula; }}

		private CMD_DNFHSetConfig fldDNFHSetConfig;
		public CMD_DNFHSetConfig DNFHSetConfig { get { return (fldDNFHSetConfig == null)? (fldDNFHSetConfig = new CMD_DNFHSetConfig()): fldDNFHSetConfig; }}

		private CMD_DNFHGetConfig fldDNFHGetConfig;
		public CMD_DNFHGetConfig DNFHGetConfig { get { return (fldDNFHGetConfig == null)? (fldDNFHGetConfig = new CMD_DNFHGetConfig()): fldDNFHGetConfig; }}

		private CMD_DNFHGetOtrosTrib fldDNFHGetOtrosTrib;
		public CMD_DNFHGetOtrosTrib DNFHGetOtrosTrib { get { return (fldDNFHGetOtrosTrib == null)? (fldDNFHGetOtrosTrib = new CMD_DNFHGetOtrosTrib()): fldDNFHGetOtrosTrib; }}

		private CMD_DNFHOtroTributo fldDNFHOtroTributo;
		public CMD_DNFHOtroTributo DNFHOtroTributo { get { return (fldDNFHOtroTributo == null)? (fldDNFHOtroTributo = new CMD_DNFHOtroTributo()): fldDNFHOtroTributo; }}
	}

	public partial class ActiveXObject
	{
 
		public CSistema Sistema { get; private set; }
 
		public CDiagnostico Diagnostico { get; private set; }
 
		public CConfiguracion Configuracion { get; private set; }
 
		public CImpresora Impresora { get; private set; }
 
		public CJornadaFiscal JornadaFiscal { get; private set; }
 
		public CDescarga Descarga { get; private set; }
 
		public CTicket Ticket { get; private set; }
 
		public CTicketFactura TicketFactura { get; private set; }
 
		public CNotaDeCredito NotaDeCredito { get; private set; }
 
		public CDNFHGenericos DNFHGenericos { get; private set; }
 
		public CDNFAutorizados DNFAutorizados { get; private set; }
 
		public CDNFHHomologados DNFHHomologados { get; private set; }

		public ActiveXObject()
		{
 
			Sistema = new CSistema();
 
			Diagnostico = new CDiagnostico();
 
			Configuracion = new CConfiguracion();
 
			Impresora = new CImpresora();
 
			JornadaFiscal = new CJornadaFiscal();
 
			Descarga = new CDescarga();
 
			Ticket = new CTicket();
 
			TicketFactura = new CTicketFactura();
 
			NotaDeCredito = new CNotaDeCredito();
 
			DNFHGenericos = new CDNFHGenericos();
 
			DNFAutorizados = new CDNFAutorizados();
 
			DNFHHomologados = new CDNFHHomologados();
		}
	}
}
