// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ObtenerErrorInterno.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Sistema
{
	public class MI_ObtenerErrorInterno : MInput
	{

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0004, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ObtenerErrorInterno  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ObtenerErrorInterno 
	    : CMD_CommandBase<MI_ObtenerErrorInterno, MO_ObtenerErrorInterno>
	{
		public override CmdStatus Status {  get { return CmdStatus.Compatible; }}
		public override string Nombre { get { return "ObtenerErrorInterno"; }}
		public override int Opcode { get { return 0x0004; }}
		public override string Description { get { return "Obtiene el código de error correspondiente, si se produjo un error en operaciones internas."; }}

		// Ctor
		public CMD_ObtenerErrorInterno()
		{
			Input = new MI_ObtenerErrorInterno();
			Output = new MO_ObtenerErrorInterno();
		}
	}
}
