// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_DNFH1Lineas.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_DNFH1Lineas_ClassInterface
	{
		string Linea1 { get; set; }
		string Linea2 { get; set; }
		string Linea3 { get; set; }
		string Linea4 { get; set; }
		string Linea5 { get; set; }
		string Linea6 { get; set; }
		string Linea7 { get; set; }
		string Linea8 { get; set; }
		string Linea9 { get; set; }
		string Linea10 { get; set; }
		string Linea11 { get; set; }
		string Linea12 { get; set; }
		string Linea13 { get; set; }
		string Linea14 { get; set; }
		string Linea15 { get; set; }
		string Linea16 { get; set; }
		string Linea17 { get; set; }
		string Linea18 { get; set; }
		string Linea19 { get; set; }
		string Linea20 { get; set; }
		string Linea21 { get; set; }
		string Linea22 { get; set; }
		string Linea23 { get; set; }
		string Linea24 { get; set; }
		string Linea25 { get; set; }
		string Linea26 { get; set; }
		string Linea27 { get; set; }
		string Linea28 { get; set; }
		string Linea29 { get; set; }
		string Linea30 { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_DNFH1Lineas 
		: MInput
		, IMI_DNFH1Lineas_ClassInterface
	{
		public string Linea1 { get; set; }
		public string Linea2 { get; set; }
		public string Linea3 { get; set; }
		public string Linea4 { get; set; }
		public string Linea5 { get; set; }
		public string Linea6 { get; set; }
		public string Linea7 { get; set; }
		public string Linea8 { get; set; }
		public string Linea9 { get; set; }
		public string Linea10 { get; set; }
		public string Linea11 { get; set; }
		public string Linea12 { get; set; }
		public string Linea13 { get; set; }
		public string Linea14 { get; set; }
		public string Linea15 { get; set; }
		public string Linea16 { get; set; }
		public string Linea17 { get; set; }
		public string Linea18 { get; set; }
		public string Linea19 { get; set; }
		public string Linea20 { get; set; }
		public string Linea21 { get; set; }
		public string Linea22 { get; set; }
		public string Linea23 { get; set; }
		public string Linea24 { get; set; }
		public string Linea25 { get; set; }
		public string Linea26 { get; set; }
		public string Linea27 { get; set; }
		public string Linea28 { get; set; }
		public string Linea29 { get; set; }
		public string Linea30 { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0E03, extension, list);
				Append_RT(list, Linea1, -1, 0, true);
				Append_RT(list, Linea2, -1, 0, true);
				Append_RT(list, Linea3, -1, 0, true);
				Append_RT(list, Linea4, -1, 0, true);
				Append_RT(list, Linea5, -1, 0, true);
				Append_RT(list, Linea6, -1, 0, true);
				Append_RT(list, Linea7, -1, 0, true);
				Append_RT(list, Linea8, -1, 0, true);
				Append_RT(list, Linea9, -1, 0, true);
				Append_RT(list, Linea10, -1, 0, true);
				Append_RT(list, Linea11, -1, 0, true);
				Append_RT(list, Linea12, -1, 0, true);
				Append_RT(list, Linea13, -1, 0, true);
				Append_RT(list, Linea14, -1, 0, true);
				Append_RT(list, Linea15, -1, 0, true);
				Append_RT(list, Linea16, -1, 0, true);
				Append_RT(list, Linea17, -1, 0, true);
				Append_RT(list, Linea18, -1, 0, true);
				Append_RT(list, Linea19, -1, 0, true);
				Append_RT(list, Linea20, -1, 0, true);
				Append_RT(list, Linea21, -1, 0, true);
				Append_RT(list, Linea22, -1, 0, true);
				Append_RT(list, Linea23, -1, 0, true);
				Append_RT(list, Linea24, -1, 0, true);
				Append_RT(list, Linea25, -1, 0, true);
				Append_RT(list, Linea26, -1, 0, true);
				Append_RT(list, Linea27, -1, 0, true);
				Append_RT(list, Linea28, -1, 0, true);
				Append_RT(list, Linea29, -1, 0, true);
				Append_RT(list, Linea30, -1, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_DNFH1Lineas_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_DNFH1Lineas  
		: MOutput
		, IMO_DNFH1Lineas_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_DNFH1Lineas_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_DNFH1Lineas_ClassInterface Input { get; }
		IMO_DNFH1Lineas_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_DNFH1Lineas 
	    : CMD_Generic
		, ICMD_DNFH1Lineas_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "DNFH1Lineas"; }}
		public override int Opcode { get { return 0x0E03; }}
		public override string Description { get { return "Imprime varias líneas de texto en el documento no fiscal abierto."; }}

		public IMI_DNFH1Lineas_ClassInterface Input { get; protected set; }
		public IMO_DNFH1Lineas_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_DNFH1Lineas();
			Output = new MO_DNFH1Lineas();
		}

		// Ctor
		public CMD_DNFH1Lineas()
		{
			SetDefaults();
		}
	}

}
