// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_DNFH1Info.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_DNFH1Info_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_DNFH1Info 
		: MInput
		, IMI_DNFH1Info_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0E0A, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_DNFH1Info_ClassInterface
	{
		int Numero { get; set; }
		int Lineas { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_DNFH1Info  
		: MOutput
		, IMO_DNFH1Info_ClassInterface
	{
		public int Numero { get; set; }
		public int Lineas { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Numero = Extract_N(data, 5, false);
					Lineas = Extract_N(data, 8, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_DNFH1Info_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_DNFH1Info_ClassInterface Input { get; }
		IMO_DNFH1Info_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_DNFH1Info 
	    : CMD_Generic
		, ICMD_DNFH1Info_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "DNFH1Info"; }}
		public override int Opcode { get { return 0x0E0A; }}
		public override string Description { get { return "Obtiene información sobre el DNFH actualmente en curso."; }}

		public IMI_DNFH1Info_ClassInterface Input { get; protected set; }
		public IMO_DNFH1Info_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_DNFH1Info();
			Output = new MO_DNFH1Info();
		}

		// Ctor
		public CMD_DNFH1Info()
		{
			SetDefaults();
		}
	}

}
