// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_JORAudCancela.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_JORAudCancela_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_JORAudCancela 
		: MInput
		, IMI_JORAudCancela_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0816, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_JORAudCancela_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_JORAudCancela  
		: MOutput
		, IMO_JORAudCancela_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_JORAudCancela_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_JORAudCancela_ClassInterface Input { get; }
		IMO_JORAudCancela_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_JORAudCancela 
	    : CMD_Generic
		, ICMD_JORAudCancela_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "JORAudCancela"; }}
		public override int Opcode { get { return 0x0816; }}
		public override string Description { get { return "Cancela la descarga del informe de auditoría."; }}

		public IMI_JORAudCancela_ClassInterface Input { get; protected set; }
		public IMO_JORAudCancela_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_JORAudCancela();
			Output = new MO_JORAudCancela();
		}

		// Ctor
		public CMD_JORAudCancela()
		{
			SetDefaults();
		}
	}

}
