// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_JORDupliFinal.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_JORDupliFinal_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_JORDupliFinal 
		: MInput
		, IMI_JORDupliFinal_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x08F5, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_JORDupliFinal_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_JORDupliFinal  
		: MOutput
		, IMO_JORDupliFinal_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_JORDupliFinal_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_JORDupliFinal_ClassInterface Input { get; }
		IMO_JORDupliFinal_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_JORDupliFinal 
	    : CMD_Generic
		, ICMD_JORDupliFinal_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "JORDupliFinal"; }}
		public override int Opcode { get { return 0x08F5; }}
		public override string Description { get { return "Finaliza la descarga del duplicado solicitado, y la imprime si así se solicitó."; }}

		public IMI_JORDupliFinal_ClassInterface Input { get; protected set; }
		public IMO_JORDupliFinal_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_JORDupliFinal();
			Output = new MO_JORDupliFinal();
		}

		// Ctor
		public CMD_JORDupliFinal()
		{
			SetDefaults();
		}
	}

}
