// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_JORZeta.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_JORZeta_ClassInterface
	{
		bool Ignorado1 { get; set; }
		bool Ignorado2 { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_JORZeta 
		: MInput
		, IMI_JORZeta_ClassInterface
	{
		public bool Ignorado1 { get; set; }
		public bool Ignorado2 { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Ignorado1) extension |= 0x400;
				if(Ignorado2) extension |= 0x800;
				SetOpcode(0x0801, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_JORZeta_ClassInterface
	{
		int NumZeta { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_JORZeta  
		: MOutput
		, IMO_JORZeta_ClassInterface
	{
		public int NumZeta { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					NumZeta = Extract_N(data, 5, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_JORZeta_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_JORZeta_ClassInterface Input { get; }
		IMO_JORZeta_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_JORZeta 
	    : CMD_Generic
		, ICMD_JORZeta_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "JORZeta"; }}
		public override int Opcode { get { return 0x0801; }}
		public override string Description { get { return "Realiza el cierre de la jornada fiscal."; }}

		public IMI_JORZeta_ClassInterface Input { get; protected set; }
		public IMO_JORZeta_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_JORZeta();
			Output = new MO_JORZeta();
		}

		// Ctor
		public CMD_JORZeta()
		{
			SetDefaults();
		}
	}

}
