// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_JORDupliInicia.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_JORDupliInicia_ClassInterface
	{
		int TipoDoc { get; set; }
		string NumeroDoc { get; set; }
		bool Print { get; set; }
		bool Zipeado { get; set; }
		bool Pendrive { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_JORDupliInicia 
		: MInput
		, IMI_JORDupliInicia_ClassInterface
	{
		public int TipoDoc { get; set; }
		public string NumeroDoc { get; set; }
		public bool Print { get; set; }
		public bool Zipeado { get; set; }
		public bool Pendrive { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Print) extension |= 0x01;
				if(Zipeado) extension |= 0x04;
				if(Pendrive) extension |= 0x10;
				SetOpcode(0x08F0, extension, list);
				Append_N(list, TipoDoc, 3, 0, false);
				Append_A(list, NumeroDoc, -1, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_JORDupliInicia_ClassInterface
	{
		int Largo { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_JORDupliInicia  
		: MOutput
		, IMO_JORDupliInicia_ClassInterface
	{
		public int Largo { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Largo = Extract_N(data, 10, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_JORDupliInicia_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_JORDupliInicia_ClassInterface Input { get; }
		IMO_JORDupliInicia_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_JORDupliInicia 
	    : CMD_Generic
		, ICMD_JORDupliInicia_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "JORDupliInicia"; }}
		public override int Opcode { get { return 0x08F0; }}
		public override string Description { get { return "Inicia la descarga (o reimpresión) de un documento emitido con anterioridad."; }}

		public IMI_JORDupliInicia_ClassInterface Input { get; protected set; }
		public IMO_JORDupliInicia_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_JORDupliInicia();
			Output = new MO_JORDupliInicia();
		}

		// Ctor
		public CMD_JORDupliInicia()
		{
			SetDefaults();
		}
	}

}
