// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_JORGetInfoOtrosTributosJornada.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_JORGetInfoOtrosTributosJornada_ClassInterface
	{
		int TipoDoc { get; set; }
		int NumOtrosTrib { get; set; }
		bool Discriminar { get; set; }
		bool SoloCajero { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_JORGetInfoOtrosTributosJornada 
		: MInput
		, IMI_JORGetInfoOtrosTributosJornada_ClassInterface
	{
		public int TipoDoc { get; set; }
		public int NumOtrosTrib { get; set; }
		public bool Discriminar { get; set; }
		public bool SoloCajero { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Discriminar) extension |= 0x01;
				if(SoloCajero) extension |= 0x100;
				SetOpcode(0x080C, extension, list);
				Append_N(list, TipoDoc, 3, 0, false);
				Append_N(list, NumOtrosTrib, 2, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_JORGetInfoOtrosTributosJornada_ClassInterface
	{
		decimal Total { get; set; }
		decimal TotPercepIngBrutos { get; set; }
		decimal TotPercepIVA { get; set; }
		decimal TotPercepOtras { get; set; }
		int CantOtrosTributos { get; set; }
		string DescOtroTrbuto { get; set; }
		decimal Monto { get; set; }
		int Tasa { get; set; }
		int Codigo { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_JORGetInfoOtrosTributosJornada  
		: MOutput
		, IMO_JORGetInfoOtrosTributosJornada_ClassInterface
	{
		public decimal Total { get; set; }
		public decimal TotPercepIngBrutos { get; set; }
		public decimal TotPercepIVA { get; set; }
		public decimal TotPercepOtras { get; set; }
		public int CantOtrosTributos { get; set; }
		public string DescOtroTrbuto { get; set; }
		public decimal Monto { get; set; }
		public int Tasa { get; set; }
		public int Codigo { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Total = Extract_N(data, 10, 2, false);
					TotPercepIngBrutos = Extract_N(data, 10, 2, false);
					TotPercepIVA = Extract_N(data, 10, 2, false);
					TotPercepOtras = Extract_N(data, 10, 2, false);
					CantOtrosTributos = Extract_N(data, 2, false);
					DescOtroTrbuto = Extract_RT(data, -1, true);
					Monto = Extract_N(data, 10, 2, true);
					Tasa = Extract_N(data, 4, true);
					Codigo = Extract_N(data, 2, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_JORGetInfoOtrosTributosJornada_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_JORGetInfoOtrosTributosJornada_ClassInterface Input { get; }
		IMO_JORGetInfoOtrosTributosJornada_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_JORGetInfoOtrosTributosJornada 
	    : CMD_Generic
		, ICMD_JORGetInfoOtrosTributosJornada_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "JORGetInfoOtrosTributosJornada"; }}
		public override int Opcode { get { return 0x080C; }}
		public override string Description { get { return "Devuelve información electrónica de los 'Otros Tributos' facturados en la jornada fiscal en curso."; }}

		public IMI_JORGetInfoOtrosTributosJornada_ClassInterface Input { get; protected set; }
		public IMO_JORGetInfoOtrosTributosJornada_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_JORGetInfoOtrosTributosJornada();
			Output = new MO_JORGetInfoOtrosTributosJornada();
		}

		// Ctor
		public CMD_JORGetInfoOtrosTributosJornada()
		{
			SetDefaults();
		}
	}

}
