// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_JORDupliEnumera.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_JORDupliEnumera_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_JORDupliEnumera 
		: MInput
		, IMI_JORDupliEnumera_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x08F4, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_JORDupliEnumera_ClassInterface
	{
		string Data { get; set; }
		bool Continua { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_JORDupliEnumera  
		: MOutput
		, IMO_JORDupliEnumera_ClassInterface
	{
		public string Data { get; set; }
		public bool Continua { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Data = Extract_P(data, 4000, false);
					Continua = Extract_Y(data, 1, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_JORDupliEnumera_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_JORDupliEnumera_ClassInterface Input { get; }
		IMO_JORDupliEnumera_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_JORDupliEnumera 
	    : CMD_Generic
		, ICMD_JORDupliEnumera_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "JORDupliEnumera"; }}
		public override int Opcode { get { return 0x08F4; }}
		public override string Description { get { return "Continúa la descarga de un documento cuya copia se solicitó con anterioridad."; }}

		public IMI_JORDupliEnumera_ClassInterface Input { get; protected set; }
		public IMO_JORDupliEnumera_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_JORDupliEnumera();
			Output = new MO_JORDupliEnumera();
		}

		// Ctor
		public CMD_JORDupliEnumera()
		{
			SetDefaults();
		}
	}

}
