// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ObtenerErrorInicio.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ObtenerErrorInicio_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ObtenerErrorInicio 
		: MInput
		, IMI_ObtenerErrorInicio_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0003, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ObtenerErrorInicio_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ObtenerErrorInicio  
		: MOutput
		, IMO_ObtenerErrorInicio_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ObtenerErrorInicio_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ObtenerErrorInicio_ClassInterface Input { get; }
		IMO_ObtenerErrorInicio_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ObtenerErrorInicio 
	    : CMD_Generic
		, ICMD_ObtenerErrorInicio_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Compatible; }}
		public override string Nombre { get { return "ObtenerErrorInicio"; }}
		public override int Opcode { get { return 0x0003; }}
		public override string Description { get { return "Obtiene el código de error correspondiente, si se produjo un error al arrancar la impresora fiscal."; }}

		public IMI_ObtenerErrorInicio_ClassInterface Input { get; protected set; }
		public IMO_ObtenerErrorInicio_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ObtenerErrorInicio();
			Output = new MO_ObtenerErrorInicio();
		}

		// Ctor
		public CMD_ObtenerErrorInicio()
		{
			SetDefaults();
		}
	}

}
