// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ObtenerEstado.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ObtenerEstado_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ObtenerEstado 
		: MInput
		, IMI_ObtenerEstado_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0001, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ObtenerEstado_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ObtenerEstado  
		: MOutput
		, IMO_ObtenerEstado_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ObtenerEstado_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ObtenerEstado_ClassInterface Input { get; }
		IMO_ObtenerEstado_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ObtenerEstado 
	    : CMD_Generic
		, ICMD_ObtenerEstado_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerEstado"; }}
		public override int Opcode { get { return 0x0001; }}
		public override string Description { get { return "Obtiene los valores de estado fiscal y de impresora, en tiempo real."; }}

		public IMI_ObtenerEstado_ClassInterface Input { get; protected set; }
		public IMO_ObtenerEstado_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ObtenerEstado();
			Output = new MO_ObtenerEstado();
		}

		// Ctor
		public CMD_ObtenerEstado()
		{
			SetDefaults();
		}
	}

}
