// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_DNFHAnula.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_DNFHAnula_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_DNFHAnula 
		: MInput
		, IMI_DNFHAnula_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x1007, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_DNFHAnula_ClassInterface
	{
		int Numero { get; set; }
		string TipoDoc { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_DNFHAnula  
		: MOutput
		, IMO_DNFHAnula_ClassInterface
	{
		public int Numero { get; set; }
		public string TipoDoc { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Numero = Extract_N(data, 8, false);
					TipoDoc = Extract_L(data, 1, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_DNFHAnula_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_DNFHAnula_ClassInterface Input { get; }
		IMO_DNFHAnula_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_DNFHAnula 
	    : CMD_Generic
		, ICMD_DNFHAnula_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "DNFHAnula"; }}
		public override int Opcode { get { return 0x1007; }}
		public override string Description { get { return "Anula el documento no fiscal homologado en curso."; }}

		public IMI_DNFHAnula_ClassInterface Input { get; protected set; }
		public IMO_DNFHAnula_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_DNFHAnula();
			Output = new MO_DNFHAnula();
		}

		// Ctor
		public CMD_DNFHAnula()
		{
			SetDefaults();
		}
	}

}
