// codes[auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the codes[auto-generated] key at top. Then, the tool will skip the regeneration of this file.

// ErrorCodes.cs
// Códigos de error manejados por el firmware fiscal.
using System;
using System.Collections.Generic;
using System.Text;

namespace FiscalProto
{
    static public class ErrorCodes
    {
        static Dictionary<int, string> codes;

        static public string Get(int code)
        {
            string result;
            if (!codes.TryGetValue(code, out result))
                return "Error Desconocido";

            return result;
        }

        static ErrorCodes()
        {
            codes = new Dictionary<int, string>();
                
            // Códigos especiales
            codes[0x0000] = "";  // ERR_NONE
            codes[0x0001] = "Error interno"; // ERR_INTERNAL
            codes[0x0003] = "Error de proceso interno";  // ERR_INTERNALPROCESSING
            codes[0x0004] = "Error al grabar datos en SysLog";   // ERR_SYSLOG_DISKERROR
            codes[0x0005] = "Comando no implementado";   // ERR_NOT_IMPLEMENTED
            codes[0x0006] = "Sin memoria suficiente";    // ERR_NOT_ENOUGH_MEMORY
            codes[0x0007] = "El monto máximo por item es 9999999.99";    // ERR_OVERFLOW_ITEM
            codes[0x0008] = "El monto máximo por operación es 999999999.99"; // ERR_OVERFLOW_OPERATION
            codes[0x0009] = "El monto máximo por jornada es 99999999999.99"; // ERR_OVERFLOW_JORNADA
            codes[0x000A] = "La cantidad máxima a multiplicar es 99999.9999";    // ERR_OVERFLOW_QUANTITY
            codes[0x000B] = "El monto final de un item no puede ser negativo";   // ERR_OVERFLOW_NEGATIVE
            codes[0x000C] = "Supera el monto permitido para ticket/nc a consumidor final";   // ERR_OVERFLOW_CONSFINAL
            codes[0x0050] = "El controlador fiscal está bloqueado";  // ERR_BLOQ_GENERIC
            codes[0x0051] = "No hay espacio suficiente para iniciar una nueva transacción";  // ERR_BLOQ_NO_SPACE
            codes[0x0052] = "No hay espacio suficiente para continuar la transacción";   // ERR_BLOQ_NO_SPACE_ITEM
            codes[0x0053] = "Se llenó la memoria fiscal";    // ERR_BLOQ_FULL
            codes[0x0054] = "Solo se permiten hasta 100 desbloqueos como máximo";    // ERR_BLOQ_TOO_TECH

            codes[0x8001] = "Error interno"; // ERR_INTERNAL
            codes[0x8003] = "Error de proceso interno"; //ERR_INTERNALPROCESSING
            codes[0x8004] = "Error al grabar datos en SysLog"; // ERR_SYSLOG_DISKERROR
            codes[0x8005] = "Comando no implementado"; // ERR_NOT_IMPLEMENTED
            codes[0x8006] = "Sin memoria suficiente"; //ERR_NOT_ENOUGH_MEMORY
            codes[0x8007] = "El monto máximo por item es 9999999.99"; // ERR_OVERFLOW_ITEM
            codes[0x8008] = "El monto máximo por operación es 999999999.99"; //ERR_OVERFLOW_OPERATION
            codes[0x8009] = "El monto máximo por jornada es 99999999999.99"; //ERR_OVERFLOW_JORNADA
            codes[0x800A] = "La cantidad máxima a multiplicar es 99999.9999"; //ERR_OVERFLOW_QUANTITY
            codes[0x800B] = "El monto final de un item no puede ser negativo"; //ERR_OVERFLOW_NEGATIVE
            codes[0x800C] = "Supera el monto permitido para ticket/nc a consumidor final"; //ERR_OVERFLOW_CONSFINA
            codes[0x8050] = "El controlador fiscal está bloqueado"; //ERR_BLOQ_GENERIC
            codes[0x8051] = "No hay espacio suficiente como para iniciar una nueva transacción"; //ERR_BLOQ_NO_SPACE
            codes[0x8052] = "No hay espacio suficiente para continuar la transacción"; //ERR_BLOQ_NO_SPACE_ITEM
            codes[0x8053] = "Se llenó la memoria fiscal"; //ERR_BLOQ_FULL
            codes[0x8054] = "Solo se permiten hasta 100 desbloqueos como máximo"; //ERR_BLOQ_TOO_TECH
            codes[0x8055] = "Demasiados items en la transaccion"; //ERR_TOO_MANY_ITEMS
            codes[0x8080] = "Nombre de tecla remota de mas de 16 caracteres"; //ERR_TELEK_TOO_LONG
            codes[0x8081] = "Tecla invalida o desconocida"; //ERR_TELEK_INVALID_KEY
            codes[0x8082] = "Use papel 80mm"; //ERR_PAPER_80
            codes[0x8083] = "Use papel 57mm"; //ERR_PAPER_57

                // Errores genéricos al procesar los comandos
            codes[0x0101] = "Comando invalido para el estado actual";    // ERR_CMDINPUT_INVALID_STATE
            codes[0x0102] = "Comando invalido para el documento actual"; // ERR_CMDINPUT_INVALID_DOC
            codes[0x0103] = "Comando solo aceptado en modo tecnico"; // ERR_CMDINPUT_ONLY_TECHNICAL
            codes[0x0104] = "Comando solo aceptado sin Jumper de Servicio";  // ERR_CMDINPUT_REMOVE_TECHSWITCH
            codes[0x0105] = "Comando solo aceptado con Jumper de Servicio";  // ERR_CMDINPUT_MISSING_TECHSWITCH
            codes[0x0106] = "Comando solo aceptado sin Jumper de Uso Interno";   // ERR_CMDINPUT_REMOVE_INTSWITCH
            codes[0x0107] = "Comando solo aceptado con Jumper de Uso Interno";   // ERR_CMDINPUT_MISSING_INTSWITCH
            codes[0x0109] = "Limite de intervenciones tecnicas alcanzado";   // ERR_CMDINPUT_TOOMANY_TECH
            codes[0x010A] = "El controlador fiscal está bloqueado";  // ERR_CMDINPUT_BLOQUEADO
            codes[0x010B] = "No puede abrir DNFH en este momento"; //ERR_CMDINPUT_CANNOTPRINT

                // Errores relacionados con el protocolo
            codes[0x0201] = "El frame no es del largo minimo aceptado";  // ERR_FRAME_LENGTH
            codes[0x0202] = "Comando invalido";  // ERR_FRAME_COMMAND
            codes[0x0203] = "El comando tiene MAS campos de los que soporta";    // ERR_FRAME_TOOMANY_FIELDS
            codes[0x0204] = "El comando tiene MENOS campos de los que necesita"; // ERR_FRAME_MISSING_FIELDS
            codes[0x0205] = "Falta un campo que no opcional";    // ERR_FRAME_INVALID_OPTIONAL_USAGE
            codes[0x0206] = "Campo alfanumerico invalido";   // ERR_FRAME_INVALID_ALPHANUM
            codes[0x0207] = "Campo alfabetico invalido"; // ERR_FRAME_INVALID_ALPHA
            codes[0x0208] = "Campo numerico invalido";   // ERR_FRAME_INVALID_NUMERIC
            codes[0x0209] = "Campo binario invalido";    // ERR_FRAME_INVALID_BINARY
            codes[0x020A] = "Campo imprimible invalido"; // ERR_FRAME_INVALID_PRINTABLE
            codes[0x020B] = "Campo hexadecimal invalido";    // ERR_FRAME_INVALID_HEXADECIMAL
            codes[0x020C] = "Campo fecha invalido";  // ERR_FRAME_INVALID_DATE
            codes[0x020D] = "Campo hora invalido";   // ERR_FRAME_INVALID_TIME
            codes[0x020E] = "Campo fiscal rich text invalido";   // ERR_FRAME_INVALID_RICHTEXT
            codes[0x020F] = "Campo booleano invalido";   // ERR_FRAME_INVALID_BOOLEAN
            codes[0x0210] = "Largo del campo invalido";  // ERR_FRAME_INVALID_FIELD_LENGTH
            codes[0x0211] = "Extension del comando invalida";    // ERR_FRAME_INVALID_EXTENSION
            codes[0x0212] = "Codigo de barra no permitido";  // ERR_FRAME_BARCODE_NOT_ALLOWED
            codes[0x0213] = "Atributos de impresion no permitidos";  // ERR_FRAME_PRINTATTRIB_NOT_SUPPORTED
            codes[0x0214] = "Atributo de impresion invalido";    // ERR_FRAME_INVALID_PRINTATTRIB
            codes[0x0215] = "Codigo de barra incorrectamente definido";  // ERR_FRAME_INVALID_BARCODE
            codes[0x0216] = "La palabra total (o sus variantes) no se permite";    // ERR_FRAME_AVOID_TOTAL_STRING
            codes[0x0217] = "Importe fuera del rango habilitado";    // ERR_FRAME_OUTOFRANGE
            codes[0x0219] = "Uno de dos campos no se debe indicar";  // ERR_FRAME_AVOID_2_FIELDS
            codes[0x0250] = "Error al descargar el reporte de eventos";  // ERR_FRAME_ERROR_DOWNLOADING
            codes[0x0251] = "Secuencia de descarga del reporte de eventos invalida"; // ERR_FRAME_INVALID_SEQUENCE

                // Retornos sobre problemas de hardware
            codes[0x0301] = "Error de hardware"; // ERR_HARD_GENERAL
            codes[0x0302] = "Impresora fuera de linea";  // ERR_HARD_OFFLINE
            codes[0x0303] = "Error de Impresion";    // ERR_HARD_PRINTING
            codes[0x0304] = "Falta papel en el impresor";    // ERR_HARD_NOPAPER
            codes[0x0305] = "Poco papel disponible"; // ERR_HARD_PAPERLOW
            codes[0x0306] = "Error en carga o expulsion de papel";   // ERR_HARD_PAPERLOADING
            codes[0x0307] = "Caracteristica de impresora no soportada";  // ERR_HARD_NOTSUPPORTED
            codes[0x0308] = "Error de display";  // ERR_HARD_DISPLAY
            codes[0x0309] = "Secuencia de scan invalida";    // ERR_HARD_SCANNING
            codes[0x030A] = "Número de área de recorte(crop area) invalido"; // ERR_HARD_CROPPING
            codes[0x030B] = "Scanner no preparado";  // ERR_HARD_SCANNER_OFFLINE
            codes[0x030C] = "Resolucion de logotipo de la empresa no permitida"; // ERR_HARD_BAD_RESOLUTION
            codes[0x030D] = "Imposible imprimir documento en estacion termica";  // ERR_HARD_NO_FOR_TERMAL
            codes[0x030E] = "La memoria fiscal no está conectada";   // ERR_FISCALMEM_UNACCESIBLE
            codes[0x030F] = "Operación inválida en la memoria fiscal";   // ERR_FISCALMEM_INVALID_OPERATION
            codes[0x0310] = "Pendrive no conectado"; // ERR_PENDRIVE_NO_CONECTED
            codes[0x0311] = "Error usando el pendrive"; // ERR_PENDRIVE_GENERAL
            codes[0x0312] = "Poca memoria usando el pendrive"; // ERR_PENDRIVE_MEMORY

                // Retornos sobre inicializacion, altas y bajas
            codes[0x0401] = "Numero de serie invalido";  // ERR_INIT_SERINV
            codes[0x0404] = "Aun no se realizo al menos uno de los dos tipo de descargas requeridas para las jornadas fiscales. Descarga completa o descarga de documentos tipo A";  // ERR_INIT_MISSING_DOWNLOAD
            codes[0x0406] = "Solo puede renovar el certificado del equipo";  // ERR_INIT_ONLY_REFRESH_EQUIP
            codes[0x0430] = "Ya se hizo la inicialización criptográfica";    // ERR_INIT_BAD_HARD_SEQUENCE
            codes[0x0431] = "Certificado aun no vigente";    // ERR_INIT_BECAUSE_BEFORETHAN
            codes[0x0436] = "Secuencia de carga de certificado digital invalida";    // ERR_INIT_INVALID_SEQ_DOWNLOAD
            codes[0x0437] = "No se puede generar archivo CSR";   // ERR_INIT_CANNOT_GENERATE_CSR
            codes[0x0438] = "El certificado no tiene un emisor válido (Ej.: AFIP)";  // ERR_INIT_FAIL_CHAIN_VALID
            codes[0x0439] = "No coincide el nro de serie del CF en el certificado del equipo";   // ERR_INIT_CERT_BAD_SERIAL
            codes[0x043A] = "Certificado digital inválido (Error ASN.1)";    // ERR_INIT_INVALID_CERT
            codes[0x043B] = "No se puede validar el certificado digital";    // ERR_INIT_CANNOT_VALIDATE_CERT
            codes[0x043C] = "Certificado AFIP (CA) no encontrado";   // ERR_INIT_MISSING_AFIP_CERT
            codes[0x043D] = "Cadena de certificados no encontrada";  // ERR_INIT_MISSING_CERT_CHAIN
            codes[0x043E] = "Falta el certificado del equipo";   // ERR_INIT_MISSING_EQUIP_CERT
            codes[0x043F] = "Certificado Digital CF vencido";    // ERR_INIT_CERT_EXPIRED
            codes[0x0440] = "Clave pública inválida (¿el cert. es para otro equipo?)";   // ERR_INIT_CERT_BAD_SIGNATURE
            codes[0x0441] = "El CAF recibido para inicializar fiscalmente no es valido (o la firma no es correcta)"; // ERR_INIT_INVALID_CAF
            codes[0x0443] = "El CAF recibido no es para éste controlador fiscal (serial incorrecto)";    // ERR_INIT_CAF_SERIAL_MISMATCH
            codes[0x0444] = "El CAF recibido ya fue usado, o tiene una cuenta de bajas que no coincide"; // ERR_INIT_CAF_BAJAS_MISMATCH
            codes[0x0445] = "El CAF contiene un punto de venta inválido o fuera de rango";   // ERR_INIT_CAF_PTOVTA_INVALID
            codes[0x0451] = "Número de bajas fiscales no coincide";  // ERR_INIT_MISMATCH_SBF
            codes[0x0455] = "No puedo preservar los datos del certificado";  // ERR_INIT_CANNOT_COPY_CERT
            codes[0x0456] = "No puedo preservar la firma del firmware";  // ERR_INIT_CANNOT_COPY_SIGNATURE
            codes[0x0457] = "El controlador fiscal nunca fue dado de baja todavía";  // ERR_INIT_SBF_NEVER
            codes[0x0458] = "No puede solicitar el SAF. El CF está ya de alta";  // ERR_INIT_SAF
            codes[0x0459] = "No puedo procesar un CAF. El CF está ya de alta";   // ERR_INIT_CAF
            codes[0x045A] = "El certificado solo puede actualizarse en modo servicio técnico";   // ERR_INIT_UPDACERT_TECH
            codes[0x045B] = "El CSR solo puede solicitarse en modo servicio técnico";    // ERR_INIT_GETCSR_TECH
            codes[0x045C] = "La firma digital debe estar en base 64";    // ERR_INIT_SIGNATURE_BAD_B64

                // Retornos sobre errores de configuracion
            codes[0x0501] = "Fecha/Hora no configurada"; // ERR_CONF_MISSING_DATETIME
            codes[0x0502] = "Fecha u hora inválidos";    // ERR_CONF_ERROR_SETTING_DATETIME
            codes[0x0503] = "Fecha fuera de rango para cambio por el usuario";   // ERR_CONF_DATE_OUTOFRANGE
            codes[0x0504] = "Fecha inferior a la de la última ZETA registrada";  // ERR_CONF_DATE_PASSED_ZETA
            codes[0x0505] = "Numero de caja invalido";   // ERR_CONF_INVALID_PVTA
            codes[0x0506] = "CUIT invalido"; // ERR_CONF_INVALID_CUIT
            codes[0x0507] = "Responsabilidad frente al IVA invalida";    // ERR_CONF_INVALID_RESP
            codes[0x0508] = "Numero de línea de Encabezado/Cola invalido";   // ERR_CONF_INVALID_LINENUMBER
            codes[0x0509] = "Demasiadas fiscalizaciones";    // ERR_CONF_TOOMANY_FISC
            codes[0x050A] = "Demasiados cambios de situacion tributaria";    // ERR_CONF_TOOMANY_CHANGES_RESP
            codes[0x050B] = "Demasiados cambios del nro de Ingresos Brutos"; // ERR_CONF_TOOMANY_CHANGES_IIBB
            codes[0x0513] = "Logo de usuario invalido";  // ERR_CONF_INVALID_LOGO
            codes[0x0514] = "Secuencia de definicion de logos de usuario invalida";  // ERR_CONF_INVALID_LOGO_SEQ
            codes[0x0515] = "Configuracion de Display invalida"; // ERR_CONF_INVALID_DISPLAY_CONF
            codes[0x0516] = "Responsabilidad INVALIDA ante el IVA";  // ERR_CONF_INVALID_FISCAL_RESPON
            codes[0x0517] = "Tipo INVALIDO de factura A";    // ERR_CONF_INVALID_TIPO_FACT_A
            codes[0x0518] = "Lineas de establecimiento no configuradas"; // ERR_CONF_MISSING_STORE_ADDR
            codes[0x0519] = "Datos fiscales no configurados";    // ERR_CONF_MISSING_DATAFISC
            codes[0x0520] = "Situacion tributaria no configurada";   // ERR_CONF_MISSING_RESP
            codes[0x0521] = "Tasa de IVA estandar no configurada";   // ERR_CONF_MISSING_STD_IVA
            codes[0x0522] = "Limite de tique - factura no configurado";  // ERR_CONF_MISSING_TOPAMOUNT
            codes[0x0524] = "Monto maximo de tique-factura no permitido";    // ERR_CONF_INVALID_TOPAMOUNT
            codes[0x0525] = "Largo del logotipo de la empresa no permitido"; // ERR_CONF_INVALID_LOGO_LENGTH
            codes[0x0526] = "Posicion del logotipo de la empresa invalido";  // ERR_CONF_INVALID_LOGO_POSITION
            codes[0x0527] = "El tamaño del logotipo de la empresa excede el maximo"; // ERR_CONF_INVALID_LOGO_SIZE
            codes[0x0550] = "Identificador tributario ya estaba configurado";    // ERR_CONF_ID_ALREADY_SET
            codes[0x0555] = "Cambio de horario de verano no permitido";  // ERR_CONF_INVALID_SUMMERTIME
            codes[0x0556] = "Formato o rango, de la línea de inicio de actividades, invalido";   // ERR_CONF_INVALID_INIACT
            codes[0x0557] = "Error al grabar datos del logo en la SDCard";   // ERR_CONF_LOGO_DISKERROR
            codes[0x0558] = "Tamaño invalido del logo";  // ERR_CONF_LOGO_BAD_DIMENSIONS
            codes[0x0559] = "Los datos del logo no se mandaron como una cadena base64 valida";   // ERR_CONF_LOGO_NO_BASE64
            codes[0x055A] = "La opcion 'Usar DHCP' no está manejada";    // ERR_CONF_DHCP_NOT_ALLOWED
            codes[0x055B] = "Una dirección IP pasada no es válida."; // ERR_CONF_INVALID_IP
            codes[0x055C] = "No hay ningún cambio nuevo";    // ERR_CONF_NOTHING_CHANGED
            codes[0x055D] = "Tasa IVA estándard no válida";  // ERR_CONF_TASAIVA_INVALID
            codes[0x055E] = "Límite de Venta a 'Consumidor Final' Inválido"; // ERR_CONF_LIMITECF_INVALID
            codes[0x055F] = "Item AFIP a configurar inválido";   // ERR_CONF_INVALID_ITEM

                // Retornos sobre memoria de transacciones
            codes[0x0601] = "Memoria de transacciones llena";    // ERR_MEM_FULL_TRANSACMEM
            codes[0x0604] = "Rango de auditoria solicitado sin datos";   // ERR_MEM_INVALID_AUD_RANGE

                // Retornos sobre el manejo de base de datos
            codes[0x0701] = "No existe la DB solicitada"; // ERR_DB_BADNAME
            codes[0x0702] = "La clave no se encontro"; // ERR_DB_NOTFOUND
            codes[0x0703] = "Tabla invalida"; // ERR_DB_INVALID_TBL
            codes[0x0704] = "PLU= El precio es negativo o muy grande"; // ERR_DB_INVALID_PRECIO
            codes[0x0705] = "PLU/CLT/MP/CAJ= El nombre no puede estar vacio"; // ERR_DB_INVALID_NOM
            codes[0x0706] = "PLU= La tasa de iva debe ser de 0 a 9"; // ERR_DB_INVALID_IVA
            codes[0x0707] = "PLU= Debe emitir una ZETA"; // ERR_DB_ZETA
            codes[0x0708] = "PLU= Codigo de medida invalido";  // ERR_DB_INVALID_MEDIDA
            codes[0x0709] = "Error interno"; // ERR_DB_INTERNO
            codes[0x070A] = "CLT= El domicilio no puede estar vacio"; // ERR_DB_INVALID_DOMIC
            codes[0x070B] = "CLT= Tipo de documento invalido"; // ERR_DB_INVALID_TDOC
            codes[0x070C] = "CLT= CUIT invalido"; // ERR_DB_INVALID_CUIT
            codes[0x070D] = "CLT= Responsabilidad ante el iva INVALIDA"; // ERR_DB_INVALID_RESPON
            codes[0x070E] = "CLT= Si es RI o MO, el documento debe ser CUIT"; // ERR_DB_EXPECTED_CUIT
            codes[0x070F] = "MP= Tipo invalido"; // ERR_DB_INVALID_TIPOMP
            codes[0x0710] = "CAJERO= Clave invalida (0001 -> 9999)"; // ERR_DB_INVALID_CLAVE

                // Retornos de error sobre jornada fiscal
            codes[0x0801] = "Requiere periodo de actividades iniciado";  // ERR_JOR_MISSING_INIT
            codes[0x0802] = "Require un Cierre Z";   // ERR_JOR_MISSING_ZETA
            codes[0x0803] = "Memoria fiscal llena";  // ERR_JOR_FULL_MEMFISC
            codes[0x0804] = "Requiere jornada fiscal abierta";   // ERR_JOR_MISSING_JORFISC
            codes[0x0807] = "Error en la solicitud de datos";    // ERR_JOR_MISSING_AUDDATA
            codes[0x0808] = "Error en la solicitud de datos";    // ERR_JOR_INVALID_AUDRANGE
            codes[0x0809] = "Restan datos por auditar/ descargar";   // ERR_JOR_AUD_PENDIENT
            codes[0x080A] = "No hay más datos a descargar";  // ERR_JOR_NO_MORE_DATA
            codes[0x080B] = "No es posible abrir la jornada fiscal"; // ERR_JOR_CANNOT_OPEN_JORFISC
            codes[0x080C] = "No es posible cerrar la jornada fiscal";    // ERR_JOR_CANNOT_CLOSE_JORFISC
            codes[0x0810] = "Tipo de documento solicitado invalido"; // ERR_JOR_INVALID_TDOC
            codes[0x0811] = "Numero de documento solicitado invalido";   // ERR_JOR_INVALID_NUMDOC
            codes[0x0812] = "Documento solicitado no existente"; // ERR_JOR_MISSING_NUMDOC
            codes[0x0813] = "La copia del documento solicitado fue borrada"; // ERR_JOR_MISSING_DOC_COPY
            codes[0x0814] = "Tipo de documento no soportado";    // ERR_JOR_UNSUPPORTED_DOC
            codes[0x0815] = "Registrado para emitir documentos normales";  // ERR_JOR_REGISTERED_NORM
            codes[0x0816] = "Registrado para emitir documentos M"; // ERR_JOR_REGISTERED_M
            codes[0x0817] = "Falta descargar jornadas previas";  // ERR_JOR_MISSING_PREV_DOWNLOAD
            codes[0x0818] = "Solo se puede imprimir el cambio una unica vez dentro de la jornada";   // ERR_JOR_ONCE_PER_JOR
            codes[0x0819] = "Requiere que se encuentre establecida la linea de inicio de actividades";   // ERR_JOR_MISSING_INIACT
            codes[0x081A] = "Error interno al generar el archivo. Pruebe un rango reducido"; // ERR_JOR_ERROR_INTERNO
            codes[0x0840] = "La fecha 'hasta' del rango elegido debe ser anterior a hoy";    // ERR_DNL_PREV_TODAY
            codes[0x0841] = "La fecha 'desde del rango elegido no puede ser inferior a la fecha de alta fiscal"; // ERR_DNL_PREV_ALTA
            codes[0x0842] = "El dato (zeta_desde/fecha_desde) está fuera de rango";  // ERR_DNL_OUTOFRANGE
            codes[0x0843] = "El rango a descargar debe ser igual a los otros arhivo(s) ya descargado(s)";    // ERR_DNL_RANGE_EQUAL
            codes[0x0844] = "El rango a descargar no se puede solapar con el del ulimo archivo descargado";  // ERR_DNL_RANGE_OVERLAP
            codes[0x0845] = "La fecha desde debe ser superior a 1 dìa exactamente, de la ùltima descarga";   // ERR_DNL_RANGE_MISSING
            codes[0x0846] = "'hasta' no puede ser menor que 'desde'";    // ERR_DNL_RANGE_INVERTED
            codes[0x0847] = "Los datos pedidos ya se descargaron antes y se borraron por necesidad"; // ERR_DNL_DELETED
            codes[0x0848] = "No hay ninguna zeta emitida en el rango solicitado";    // ERR_DNL_VACIO
            codes[0x0849] = "La descarga solicitada no está en secuencia";   // ERR_DNL_SEQUENCE
            codes[0x084A] = "El certificado del equipo está vencido o es inválido";  // ERR_DNL_CERTIFICATE0
            codes[0x084B] = "El certificado intermedio de la AFIP está vencido o es inválido";   // ERR_DNL_CERTIFICATE1
            codes[0x084C] = "El certificado raiz (CA) de la AFIP está vencido o es inválido";    // ERR_DNL_CERTIFICATE2
            codes[0x084D] = "Ya se borraron hasta la Z que se indicó";   // ERR_DNL_ALREADY_DELETED
            codes[0x084E] = "No se descargaron las Z que se desea borrar";   // ERR_DNL_NOT_DOWNLOADED
            codes[0x084F] = "Parámetros de descarga de MF inválidos";    // ERR_DNL_MFARG_INVALID
            codes[0x0850] = "Ya se hicieron las 1825 descargas posibles";    // ERR_DNL_FULL
            codes[0x0851] = "Quedan 3 descargas o menos, no puede haber jornada iniciada";   // ERR_DNL_ONLY_FULL
            codes[0x0852] = "Quedan 3 descargas o menos, debe descargar hasta la ultima Z emitida";  // ERR_DNL_ONLY_FULL2
            codes[0x0853] = "No puede emitir duplicado de auditorias"; // ERR_DNL_AUDIDUPLI

                // Retornos de error sobre ticket fiscal
            codes[0x0901] = "Overflow";  // ERR_GEN_OVERFLOW
            codes[0x0902] = "Underflow"; // ERR_GEN_UNDERFLOW
            codes[0x0903] = "Demasiados items involucrados en la transaccion";   // ERR_GEN_TOOMANY_ITEMS
            codes[0x0904] = "Demasiadas tasas de impuesto utilizadas";   // ERR_GEN_TOOMANY_TAXES
            codes[0x0905] = "Demasiados descuentos / ajustes sobre subtotal involucradas en la transaccion"; // ERR_GEN_TOOMANY_SUBTOT_REFUND
            codes[0x0906] = "Demasiados pagos involucrados en la transaccion";   // ERR_GEN_TOOMANY_PAYMENTS
            codes[0x0907] = "Item no encontrado o que ya fue anulado antes"; // ERR_GEN_MISSING_ITEM
            codes[0x0908] = "Pago no encontrado";    // ERR_GEN_MISSING_PAYMENT
            codes[0x0909] = "El total debe ser mayor a cero";    // ERR_GEN_INVALID_TOTAL
            codes[0x090A] = "Se permite solo un tipo de impuestos internos"; // ERR_GEN_TOOMANY_INTTAX
            codes[0x090B] = "Impuesto interno no aceptado";  // ERR_GEN_INVALID_INTTAX
            codes[0x090C] = "La cantidad solo puede ser 1 en bonificaciones";    // ERR_GEN_BONIF_CANT1
            codes[0x090D] = "No puede usar impuestos internos en bonificaciones";    // ERR_GEN_BONIF_IMPINT
            codes[0x090E] = "El documento asociado (o su punto de venta) no es válido";  // ERR_GEN_PTOVTA_INVALID
            codes[0x090F] = "Tasa de IVA no encontrada"; // ERR_GEN_MISSING_IVA
            codes[0x0910] = "Tasa de IVA inválida";  // ERR_GEN_INVALID_IVA
            codes[0x091E] = "Período descargado demasiado grande";   // ERR_GEN_TOOBIG_JOR
            codes[0x091F] = "Ya hay un documento abierto";   // ERR_GEN_OPENED
            codes[0x0929] = "Descto/Bonif sobre un item debe emitirse inmediatamente después de una venta";  // ERR_GEN_NOPREV

                // Retornos de error sobre Ticket/Factura, Notas de Debito, Notas de Credito
            codes[0x0A01] = "No permitido luego de descuentos / ajustes sobre el subtotal";  // ERR_TK_FASE_NO_ITEMS
            codes[0x0A02] = "No permitido luego de iniciar la fase de pago"; // ERR_TK_FASE_NO_ITEMS_NOR_DESC
            codes[0x0A03] = "Tipo de item inválido"; // ERR_TK_INVALID_ITEM_TYPE
            codes[0x0A04] = "Línea de descripcion en blanco";    // ERR_TK_EMPTY_DESC
            codes[0x0A05] = "Cantidad resultante menor que cero";    // ERR_TK_CANT_LT_ZERO
            codes[0x0A06] = "Cantidad resultante mayor a lo permitido";  // ERR_TK_CANT_GT_TOP
            codes[0x0A07] = "Precio total del item mayor al permitido";  // ERR_TK_CANT_TOTAL_GT_TOP
            codes[0x0A08] = "El ticket está vacío por lo que no puede hacer descuentos o recargos";  // ERR_TK_NO_ITEMS_DESC
            codes[0x0A0A] = "Fase de pago finalizada";   // ERR_TK_FASE_PAGO_END
            codes[0x0A0B] = "Monto de pago no permitido";    // ERR_TK_INVALID_PAGO
            codes[0x0A0C] = "Monto de descuento / ajuste no permitido";  // ERR_TK_INVALID_DESC
            codes[0x0A0F] = "No permitido antes de un item"; // ERR_TK_MISSING_ITEMS
            codes[0x0A10] = "Demasiadas descripciones extras";   // ERR_TK_TOOMANY_DESC
            codes[0x0A11] = "Falta número de cupón en tarjeta de crédito/débito";    // ERR_TK_MISSING_CUPON
            codes[0x0A12] = "Falta la MARCA de la tarjeta de crédito/débito";    // ERR_TK_MISSING_MARCA
            codes[0x0A31] = "Codigo de tipo de pago invalido";   // ERR_TK_INVALID_PAYCODE
            codes[0x0A32] = "Imposible aplicar el descuento/ ajuste particular. No se encontró un item que corresponda a la misma tasa de IVA y codigo de condición frente al IVA";  // ERR_TK_DESC_CANNOT_MATCH_ITEM
            codes[0x0A33] = "Operacion no permitida luego de Otros tributos";    // ERR_TK_FASE_INVALID_AFTER_TRIBUT
            codes[0x0A34] = "Otros tributos del tipo percepciones no soportado en Tique y Tique Nota de Credito";    // ERR_TK_FASE_INVALID_TRIBUT

                // Retornos sobre documento fiscal no homologados
            codes[0x0B01] = "Tipo de documento del comprador invalido";  // ERR_TF_INVALID_DOCTYPE
            codes[0x0B02] = "Maximo valor aceptado fue superado";    // ERR_TF_OVERFLOW
            codes[0x0B03] = "CUIT / CUIL invalido";  // ERR_TF_INVALID_CUIT
            codes[0x0B04] = "Tipo de otros tributo invalido";    // ERR_TF_INVALID_TRIBUT
            codes[0x0B05] = "Exceso en la cantidad de líneas de separacion de la firma"; // ERR_TF_INVALID_NUM_BLANKSIGN
            codes[0x0B06] = "Monto cero de otros tributos no permitido"; // ERR_TF_INVALID_ZERO_TRIBUT
            codes[0x0B07] = "Demasiados Otros Tributos involucradas en la transaccion";  // ERR_TF_TOOMANY_TRIBUT
            codes[0x0B08] = "Otro tributo no encontrado";    // ERR_TF_TRIBUT_NOTFOUND
            codes[0x0B09] = "Operacion no permitida luego de Otros Tributos";    // ERR_TF_FASE_AFTER_TRIBUT
            codes[0x0B0A] = "Exceso de operaciones dentro del documento con triplicado"; // ERR_TF_TOOMANY_ITEMS
            codes[0x0B0B] = "Tique factura del turista solo es aceptado en tique - factura B";   // ERR_TF_TURIST_ONLY_B
            codes[0x0B0C] = "Datos del turista invalidos";   // ERR_TF_INVALID_TURIST
            codes[0x0B0D] = "Número de documento invalido";  // ERR_TF_INVALID_DOC
            codes[0x0B0E] = "Documento no soportado por el mecanismo de impresion";  // ERR_TF_UNSUPPORTED_DOC
            codes[0x0B11] = "Tipo de documento asociado invalido";   // ERR_TF_INVALID_ASSOCDOC
            codes[0x0B12] = "Punto de venta de documento asociado invalido"; // ERR_TF_INVALID_ASSOCPV
            codes[0x0B13] = "Numero de documento asociado invalido"; // ERR_TF_INVALID_ASSOCNUM
            codes[0x0B15] = "Número(#) de otros tributos con valor cero no permitido";   // ERR_TF_INVALID_TRIBUT_ZERO
            codes[0x0B16] = "Número (#) de otros tributos invalido"; // ERR_TF_INVALID_TRIBUT_NUM
            codes[0x0B17] = "No existen otros tributos"; // ERR_TF_MISSING_TRIBUT
            codes[0x0B18] = "Datos invalidos del transportista, al emitir Remito X/R";   // ERR_TF_INVALID_TRANSPORTISTA
            codes[0x0B19] = "Tipo de documento del tercero invalido";    // ERR_TF_INVALID_TDOC_TERCERO
            codes[0x0B1A] = "CUIT /CUIL del tercero invalido";   // ERR_TF_INVALID_CUIT_TERCERO
            codes[0x0B1B] = "Datos invalidos del chofer";    // ERR_TF_INVALID_CHOFER
            codes[0x0B1D] = "Responsabilidad frente al IVA del tercero invalida";    // ERR_TF_INVALID_RESPON_TERCERO

                // Otros retornos de error

                // Retornos de error sobre la configuración de ethernet

                // Sección sin uso (0x0E)

                // Sección sin uso (0x0F)

                // Sección sin uso (0x10)
            codes[0x1003] = "Error interno al sumar monto de importe en un DNF"; // ERR_DFNH_INTERNO
            codes[0x1004] = "Pagos no soportado en DNFH Presupuesto X, Remito R/X";  // ERR_DFNH_INVALID_PAYMENTS
            codes[0x1005] = "Tipo de item no soportado en DNFH Remito R/X, Recibo X o Donaciones";   // ERR_DFNH_INVALID_ITEM
            codes[0x1006] = "Descuentos / Recargos no permitido en DNFH Remito R/X, Recibo X o Donaciones";  // ERR_DFNH_INVALID_DESC
            codes[0x1007] = "Solamente se soporta un unico ítem en Donaciones";  // ERR_DFNH_INVALID_DONAC
            codes[0x1008] = "La cantidad del item debe ser uno en Donaciones y Recibo X";    // ERR_DFNH_CANT_MUSTBE_ONE
            codes[0x1014] = "Operación no soportada en documentos no fiscales";  // ERR_DFNH_UNSUPPORTED
            codes[0x1016] = "El documento no fiscal no puede ser cerrado en cero";   // ERR_DNFH_NO_CERO

                // Sección sin uso (0x11)
            codes[0x1105] = "Codigo de unidad de medida reservado";  // ERR_OTRO_RESERVED
            codes[0x1106] = "Codigo de condicion frente al IVA invalido";    // ERR_OTRO_INVALID_CONDIVA
            codes[0x1107] = "Solo se permite una Condicion frente al IVA del tipo Gravado (observar que la tasa de IVA es distinto de Cero)";    // ERR_OTRO_GRAVADO_CONDIVA
            codes[0x1108] = "Codigo de otros tributos invalido"; // ERR_OTRO_INVALID_TRIBUTCODE
            codes[0x1109] = "Codigo de otros tributos no permitido"; // ERR_OTRO_INVALID_TRIBUT

                // Sección sin uso (0x12)
            codes[0x1201] = "Cable de red desconectado"; // ERR_ETH_CABLE_DISCON
            codes[0x1202] = "Direccion IP invalida"; // ERR_ETH_INVALID_IP
            codes[0x1203] = "Mascara de red invalida";   // ERR_ETH_INVALID_MASK
            codes[0x1204] = "Direccion de puerta de enlace predeterminada invalida"; // ERR_ETH_INVALID_GATEWAY
            codes[0x1205] = "Error en DHCP"; // ERR_ETH_DHCP_ERROR
            codes[0x1206] = "Error al aplicar la configuracion";  // ERR_ETH_INVALID_CONFIG
            
            // Sección sin uso (0x13)

            // Sección sin uso (0x14)

            // Sección sin uso (0x15)

            // Sección sin uso (0x16)
        }
    }
}