// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ActivaImpresionArqueo.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Configuracion
{
	public class MI_ActivaImpresionArqueo : MInput
	{

		[Category("Extension")]
		[Description(
			"Imprime o no el arqueo\n" +
			"false: No, true: Si")]
		public bool Print { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Print) extension |= 0x01;
				SetOpcode(0x0552, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ActivaImpresionArqueo  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ActivaImpresionArqueo 
	    : CMD_CommandBase<MI_ActivaImpresionArqueo, MO_ActivaImpresionArqueo>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ActivaImpresionArqueo"; }}
		public override int Opcode { get { return 0x0552; }}
		public override string Description { get { return "Activa o desactiva la impresión de los arqueos al final de los informes de 'salida de cajeros' o 'total de ventas'."; }}

		// Ctor
		public CMD_ActivaImpresionArqueo()
		{
			Input = new MI_ActivaImpresionArqueo();
			Output = new MO_ActivaImpresionArqueo();
		}
	}
}
