// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ConfigInfoEstab.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Configuracion
{
	public class MI_ConfigInfoEstab : MInput
	{

		[Description("Texto a configurar en la linea indicada."), Category("Datos")]
		public string Texto { get; set; }

		[Category("Extension")]
		[Description(
			"Imprime reporte con la configuración del establecimiento.\n" +
			"false: Si, true: No")]
		public bool Print { get; set; }

		[Description("Indica el tipo de informacion que se configurara para el establecimiento"), Category("Extension")]
		public CIE_Linea Linea { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Print) extension |= 0x1000;
				extension |= (((int) Linea) & 0x000F);
				SetOpcode(0x050E, extension, list);
				Append_RT(list, Texto, -1, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ConfigInfoEstab  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ConfigInfoEstab 
	    : CMD_CommandBase<MI_ConfigInfoEstab, MO_ConfigInfoEstab>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ConfigInfoEstab"; }}
		public override int Opcode { get { return 0x050E; }}
		public override string Description { get { return "Configura los textos de las lineas que brindan información acerca del establecimiento."; }}

		// Ctor
		public CMD_ConfigInfoEstab()
		{
			Input = new MI_ConfigInfoEstab();
			Output = new MO_ConfigInfoEstab();
		}
	}

	public enum CIE_Linea 
	{
		DomComercial_1 = 0,	// 0000
		DomComercial_2 = 1,	// 0001
		DomComercial_3 = 2,	// 0010
		NomFantasia_1 = 3,	// 0011
		NomFantasia_2 = 4,	// 0100
		NomFantasia_3 = 5,	// 0101
		IngBrutos = 6,	// 0110
		InicioActiv = 9,	// 1001
	};
}
