// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ResetFabrica.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Configuracion
{
	public class MI_ResetFabrica : MInput
	{

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0564, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ResetFabrica  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ResetFabrica 
	    : CMD_CommandBase<MI_ResetFabrica, MO_ResetFabrica>
	{
		public override CmdStatus Status {  get { return CmdStatus.Nada; }}
		public override string Nombre { get { return "ResetFabrica"; }}
		public override int Opcode { get { return 0x0564; }}
		public override string Description { get { return "Elimina las configuraciones del usuario volviendo a establecer los valores estándard de fábrica."; }}

		// Ctor
		public CMD_ResetFabrica()
		{
			Input = new MI_ResetFabrica();
			Output = new MO_ResetFabrica();
		}
	}
}
