// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ObtenerEncabezado.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Configuracion
{
	public class MI_ObtenerEncabezado : MInput
	{

		[Description("Número de linea de encabezado a obtener."), Category("Datos")]
		public int Index { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0509, extension, list);
				Append_N(list, Index, 3, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ObtenerEncabezado  : MOutput
	{

		[Description("El texto establecido en el encabezamiento."), Category("Datos"), ReadOnly(true)]
		public string Texto { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Texto = Extract_RT(data, -1, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ObtenerEncabezado 
	    : CMD_CommandBase<MI_ObtenerEncabezado, MO_ObtenerEncabezado>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerEncabezado"; }}
		public override int Opcode { get { return 0x0509; }}
		public override string Description { get { return "Obtiene el texto configurado en una línea determinada del encabezado."; }}

		// Ctor
		public CMD_ObtenerEncabezado()
		{
			Input = new MI_ObtenerEncabezado();
			Output = new MO_ObtenerEncabezado();
		}
	}
}
