// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ConfigRespIVA.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Configuracion
{
	public class MI_ConfigRespIVA : MInput
	{

		[Description("Responsabilidad ante el IVA."), Category("Datos")]
		public string ResponCode { get; set; }

		[Description("Tipo de ticket factura A."), Category("Datos")]
		public int TipoTicket { get; set; }

		[Description("Para RI con leyenda, la leyenda a usar."), Category("Datos")]
		public string Leyenda { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0504, extension, list);
				Append_P(list, ResponCode, 1, 0, false);
				Append_N(list, TipoTicket, 1, 0, true);
				Append_RT(list, Leyenda, 60, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ConfigRespIVA  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ConfigRespIVA 
	    : CMD_CommandBase<MI_ConfigRespIVA, MO_ConfigRespIVA>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ConfigRespIVA"; }}
		public override int Opcode { get { return 0x0504; }}
		public override string Description { get { return "Configura la responsabilidad que tendrá el usuario frente al IVA."; }}
		public override bool Private { get { return true; }}

		// Ctor
		public CMD_ConfigRespIVA()
		{
			Input = new MI_ConfigRespIVA();
			Output = new MO_ConfigRespIVA();
		}
	}
}
