// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ObtenerConfigClaves.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Configuracion
{
	public class MI_ObtenerConfigClaves : MInput
	{

		[Category("Extension")]
		[Description(
			"Imprime documento con la configuración de las claves.\n" +
			"false: No, true: Si")]
		public bool Print { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Print) extension |= 0x01;
				SetOpcode(0x0522, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ObtenerConfigClaves  : MOutput
	{

		[Description("Tipo de algoritmo (0=RSA)."), Category("Datos"), ReadOnly(true)]
		public int TipoAlgo { get; set; }

		[Description("Datos de la clave pública."), Category("Datos"), ReadOnly(true)]
		public byte[] PubKey { get; set; }

		[Description("Fecha de generación."), Category("Datos"), ReadOnly(true)]
		public int FechaGen { get; set; }

		[Description("Hora de generación."), Category("Datos"), ReadOnly(true)]
		public int HoraGen { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					TipoAlgo = Extract_N(data, 1, false);
					PubKey = Extract_B(data, -1, false);
					FechaGen = Extract_D(data, 6, false);
					HoraGen = Extract_T(data, 6, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ObtenerConfigClaves 
	    : CMD_CommandBase<MI_ObtenerConfigClaves, MO_ObtenerConfigClaves>
	{
		public override CmdStatus Status {  get { return CmdStatus.Nada; }}
		public override string Nombre { get { return "ObtenerConfigClaves"; }}
		public override int Opcode { get { return 0x0522; }}
		public override string Description { get { return "Obtiene los valores de configuración de la clave generada para firma digital."; }}

		// Ctor
		public CMD_ObtenerConfigClaves()
		{
			Input = new MI_ObtenerConfigClaves();
			Output = new MO_ObtenerConfigClaves();
		}
	}
}
