// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_LogoEliminar.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Configuracion
{
	public class MI_LogoEliminar : MInput
	{

		[Description("Numero de logo (0-9) a eliminar, de los 10 disponibles."), Category("Datos")]
		public int Indice { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0534, extension, list);
				Append_N(list, Indice, 1, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_LogoEliminar  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_LogoEliminar 
	    : CMD_CommandBase<MI_LogoEliminar, MO_LogoEliminar>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "LogoEliminar"; }}
		public override int Opcode { get { return 0x0534; }}
		public override string Description { get { return "Elimina el logo del usuario."; }}

		// Ctor
		public CMD_LogoEliminar()
		{
			Input = new MI_LogoEliminar();
			Output = new MO_LogoEliminar();
		}
	}
}
