// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ObtenerCola.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Configuracion
{
	public class MI_ObtenerCola : MInput
	{

		[Description("Número de linea de cola a obtener."), Category("Datos")]
		public int Index { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x050B, extension, list);
				Append_N(list, Index, 3, 0, false);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ObtenerCola  : MOutput
	{

		[Description("El texto establecido en la cola."), Category("Datos"), ReadOnly(true)]
		public string Texto { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					Texto = Extract_RT(data, -1, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ObtenerCola 
	    : CMD_CommandBase<MI_ObtenerCola, MO_ObtenerCola>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerCola"; }}
		public override int Opcode { get { return 0x050B; }}
		public override string Description { get { return "Obtiene el texto configurado en una línea determinada de la cola."; }}

		// Ctor
		public CMD_ObtenerCola()
		{
			Input = new MI_ObtenerCola();
			Output = new MO_ObtenerCola();
		}
	}
}
