// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_JORZeta.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Jornada_Fiscal
{
	public class MI_JORZeta : MInput
	{

		[Category("Extension")]
		[Description(
			"Ignorado\n" +
			"false: No, true: Si")]
		public bool Ignorado1 { get; set; }

		[Category("Extension")]
		[Description(
			"Ignorado\n" +
			"false: No, true: Si")]
		public bool Ignorado2 { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Ignorado1) extension |= 0x400;
				if(Ignorado2) extension |= 0x800;
				SetOpcode(0x0801, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_JORZeta  : MOutput
	{

		[Description("Número de cierre diario (Z)."), Category("Datos"), ReadOnly(true)]
		public int NumZeta { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					NumZeta = Extract_N(data, 5, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_JORZeta 
	    : CMD_CommandBase<MI_JORZeta, MO_JORZeta>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "JORZeta"; }}
		public override int Opcode { get { return 0x0801; }}
		public override string Description { get { return "Realiza el cierre de la jornada fiscal."; }}

		// Ctor
		public CMD_JORZeta()
		{
			Input = new MI_JORZeta();
			Output = new MO_JORZeta();
		}
	}
}
