// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_IniciaAltaFiscal.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Inicializacion
{
	public class MI_IniciaAltaFiscal : MInput
	{

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0440, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_IniciaAltaFiscal  : MOutput
	{

		[Description("SAF (Solicitud de Alta Fiscal) a enviar a la AFIP."), Category("Datos"), ReadOnly(true)]
		public string SAF { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					SAF = Extract_P(data, 5500, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_IniciaAltaFiscal 
	    : CMD_CommandBase<MI_IniciaAltaFiscal, MO_IniciaAltaFiscal>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "IniciaAltaFiscal"; }}
		public override int Opcode { get { return 0x0440; }}
		public override string Description { get { return "Comienza el proceso de descarga del archivo SAF, para dar el alta fiscal del controlador."; }}

		// Ctor
		public CMD_IniciaAltaFiscal()
		{
			Input = new MI_IniciaAltaFiscal();
			Output = new MO_IniciaAltaFiscal();
		}
	}
}
