// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ObtenerSerializacion.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Inicializacion
{
	public class MI_ObtenerSerializacion : MInput
	{

		[Category("Extension")]
		[Description(
			"Imprime o no un documento con los datos de serializacion\n" +
			"false: No, true: Si")]
		public bool Print { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Print) extension |= 0x01;
				SetOpcode(0x0402, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ObtenerSerializacion  : MOutput
	{

		[Description("Número de serie."), Category("Datos"), ReadOnly(true)]
		public string NumSerie { get; set; }

		[Description("Fecha de serialización."), Category("Datos"), ReadOnly(true)]
		public int FechaSerie { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					NumSerie = Extract_P(data, 22, false);
					FechaSerie = Extract_D(data, 6, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ObtenerSerializacion 
	    : CMD_CommandBase<MI_ObtenerSerializacion, MO_ObtenerSerializacion>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerSerializacion"; }}
		public override int Opcode { get { return 0x0402; }}
		public override string Description { get { return "Obtiene los datos de serialización configurados."; }}

		// Ctor
		public CMD_ObtenerSerializacion()
		{
			Input = new MI_ObtenerSerializacion();
			Output = new MO_ObtenerSerializacion();
		}
	}
}
