// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_DiagEquipo.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Diagnostico
{
	public class MI_DiagEquipo : MInput
	{

		[Category("Extension")]
		[Description(
			"Estación por la que imprime el documento\n" +
			"false: Rollo, true: Slip")]
		public bool Estacion { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Estacion) extension |= 0x01;
				SetOpcode(0x0201, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_DiagEquipo  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_DiagEquipo 
	    : CMD_CommandBase<MI_DiagEquipo, MO_DiagEquipo>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DiagEquipo"; }}
		public override int Opcode { get { return 0x0201; }}
		public override string Description { get { return "Imprime un documento con las características del mecanismo impresor."; }}

		// Ctor
		public CMD_DiagEquipo()
		{
			Input = new MI_DiagEquipo();
			Output = new MO_DiagEquipo();
		}
	}
}
