// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ObtenerInfoCertif.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Diagnostico
{
	public class MI_ObtenerInfoCertif : MInput
	{

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0240, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ObtenerInfoCertif  : MOutput
	{

		[Description("Indica si el certificado raíz es válido."), Category("Datos"), ReadOnly(true)]
		public bool RootCertValid { get; set; }

		[Description("Fecha desde la cuál está vigente el certificado raíz."), Category("Datos"), ReadOnly(true)]
		public int RootCertFechaInicio { get; set; }

		[Description("Fecha hasta la cuál está vigente el certificado raíz."), Category("Datos"), ReadOnly(true)]
		public int RootCertFechaFinal { get; set; }

		[Description("Indica si el certificado del controlador fiscal es válido."), Category("Datos"), ReadOnly(true)]
		public bool CFCertValid { get; set; }

		[Description("Fecha desde la cuál está vigente el certificado del controlador fiscal."), Category("Datos"), ReadOnly(true)]
		public int CFCertFechaInicio { get; set; }

		[Description("Fecha hasta la cuál está vigente el certificado del controlador fiscal."), Category("Datos"), ReadOnly(true)]
		public int CFCertFechaFinal { get; set; }

		[Description("La fecha actual del controlador fiscal."), Category("Datos"), ReadOnly(true)]
		public int Fecha { get; set; }

		[Description("Número de serie del controlador fiscal."), Category("Datos"), ReadOnly(true)]
		public string Serie { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					RootCertValid = Extract_Y(data, 1, false);
					RootCertFechaInicio = Extract_D(data, 6, false);
					RootCertFechaFinal = Extract_D(data, 6, false);
					CFCertValid = Extract_Y(data, 1, false);
					CFCertFechaInicio = Extract_D(data, 6, false);
					CFCertFechaFinal = Extract_D(data, 6, false);
					Fecha = Extract_D(data, 6, false);
					Serie = Extract_A(data, 16, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ObtenerInfoCertif 
	    : CMD_CommandBase<MI_ObtenerInfoCertif, MO_ObtenerInfoCertif>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerInfoCertif"; }}
		public override int Opcode { get { return 0x0240; }}
		public override string Description { get { return "Obtiene información acerca de los certificados instalados en el controlador fiscal."; }}

		// Ctor
		public CMD_ObtenerInfoCertif()
		{
			Input = new MI_ObtenerInfoCertif();
			Output = new MO_ObtenerInfoCertif();
		}
	}
}
