// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ObtenerConfigCuchilla.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Impresora
{
	public class MI_ObtenerConfigCuchilla : MInput
	{

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0761, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ObtenerConfigCuchilla  : MOutput
	{

		[Description("Indica si está o no configurado el corte inteligente de papel en la estación de rollo."), Category("Datos"), ReadOnly(true)]
		public bool CorteInteligenteActivo { get; set; }

		[Description("Indica si la cuchilla está o no globalmente desactivada."), Category("Datos"), ReadOnly(true)]
		public bool CuchillaDesactivada { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					CorteInteligenteActivo = Extract_Y(data, 1, false);
					CuchillaDesactivada = Extract_Y(data, 1, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ObtenerConfigCuchilla 
	    : CMD_CommandBase<MI_ObtenerConfigCuchilla, MO_ObtenerConfigCuchilla>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerConfigCuchilla"; }}
		public override int Opcode { get { return 0x0761; }}
		public override string Description { get { return "Obtiene la configuracion actual de la cuchilla de corte de ticket."; }}

		// Ctor
		public CMD_ObtenerConfigCuchilla()
		{
			Input = new MI_ObtenerConfigCuchilla();
			Output = new MO_ObtenerConfigCuchilla();
		}
	}
}
