// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_ConfigCuchilla.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Impresora
{
	public class MI_ConfigCuchilla : MInput
	{

		[Category("Extension")]
		[Description(
			"Activa o no el corte inteligente de papel.\n" +
			"false: No, true: Si")]
		public bool CorteParcial { get; set; }

		[Category("Extension")]
		[Description(
			"Activa o desactiva globalmente la cuchilla.\n" +
			"false: No, true: Si")]
		public bool DesactivaCuchilla { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(CorteParcial) extension |= 0x01;
				if(DesactivaCuchilla) extension |= 0x02;
				SetOpcode(0x0760, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_ConfigCuchilla  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_ConfigCuchilla 
	    : CMD_CommandBase<MI_ConfigCuchilla, MO_ConfigCuchilla>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ConfigCuchilla"; }}
		public override int Opcode { get { return 0x0760; }}
		public override string Description { get { return "Configura funcionamiento de la cuchilla del impresor."; }}

		// Ctor
		public CMD_ConfigCuchilla()
		{
			Input = new MI_ConfigCuchilla();
			Output = new MO_ConfigCuchilla();
		}
	}
}
