// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_TFGetPago.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_TFGetPago_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_TFGetPago 
		: MInput
		, IMI_TFGetPago_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0B0C, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_TFGetPago_ClassInterface
	{
		decimal TotalPagado { get; set; }
		decimal TotalTicket { get; set; }
		decimal Vuelto { get; set; }
		int CantPagos { get; set; }
		int CantPagosMax { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_TFGetPago  
		: MOutput
		, IMO_TFGetPago_ClassInterface
	{
		public decimal TotalPagado { get; set; }
		public decimal TotalTicket { get; set; }
		public decimal Vuelto { get; set; }
		public int CantPagos { get; set; }
		public int CantPagosMax { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					TotalPagado = Extract_N(data, 10, 2, false);
					TotalTicket = Extract_N(data, 10, 2, false);
					Vuelto = Extract_N(data, 10, 2, false);
					CantPagos = Extract_N(data, 1, false);
					CantPagosMax = Extract_N(data, 1, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_TFGetPago_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_TFGetPago_ClassInterface Input { get; }
		IMO_TFGetPago_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_TFGetPago 
	    : CMD_Generic
		, ICMD_TFGetPago_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "TFGetPago"; }}
		public override int Opcode { get { return 0x0B0C; }}
		public override string Description { get { return "Obtiene información de pagos de la operación en curso."; }}

		public IMI_TFGetPago_ClassInterface Input { get; protected set; }
		public IMO_TFGetPago_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_TFGetPago();
			Output = new MO_TFGetPago();
		}

		// Ctor
		public CMD_TFGetPago()
		{
			SetDefaults();
		}
	}

}
