// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_TFGetOtrosTrib.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_TFGetOtrosTrib_ClassInterface
	{
		int Indice { get; set; }
		bool Discriminar { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_TFGetOtrosTrib 
		: MInput
		, IMI_TFGetOtrosTrib_ClassInterface
	{
		public int Indice { get; set; }
		public bool Discriminar { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Discriminar) extension |= 0x01;
				SetOpcode(0x0B0F, extension, list);
				Append_N(list, Indice, 2, 0, true);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_TFGetOtrosTrib_ClassInterface
	{
		decimal TotalOtrosTrib { get; set; }
		decimal TotalOtrosTrib_Percepciones_IIBB { get; set; }
		decimal TotalOtrosTrib_Percepciones_IVA { get; set; }
		decimal TotalOtrosTrib_Percepciones_Otras { get; set; }
		int CantOtrosTrib { get; set; }
		string Descrip { get; set; }
		decimal Total { get; set; }
		int Tasa { get; set; }
		int Codigo { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_TFGetOtrosTrib  
		: MOutput
		, IMO_TFGetOtrosTrib_ClassInterface
	{
		public decimal TotalOtrosTrib { get; set; }
		public decimal TotalOtrosTrib_Percepciones_IIBB { get; set; }
		public decimal TotalOtrosTrib_Percepciones_IVA { get; set; }
		public decimal TotalOtrosTrib_Percepciones_Otras { get; set; }
		public int CantOtrosTrib { get; set; }
		public string Descrip { get; set; }
		public decimal Total { get; set; }
		public int Tasa { get; set; }
		public int Codigo { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					TotalOtrosTrib = Extract_N(data, 10, 2, false);
					TotalOtrosTrib_Percepciones_IIBB = Extract_N(data, 10, 2, false);
					TotalOtrosTrib_Percepciones_IVA = Extract_N(data, 10, 2, false);
					TotalOtrosTrib_Percepciones_Otras = Extract_N(data, 10, 2, false);
					CantOtrosTrib = Extract_N(data, 2, false);
					Descrip = Extract_RT(data, -1, true);
					Total = Extract_N(data, 10, 2, true);
					Tasa = Extract_N(data, 4, true);
					Codigo = Extract_N(data, 2, true);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_TFGetOtrosTrib_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_TFGetOtrosTrib_ClassInterface Input { get; }
		IMO_TFGetOtrosTrib_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_TFGetOtrosTrib 
	    : CMD_Generic
		, ICMD_TFGetOtrosTrib_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.EnCurso; }}
		public override string Nombre { get { return "TFGetOtrosTrib"; }}
		public override int Opcode { get { return 0x0B0F; }}
		public override string Description { get { return "Obtiene información detallada sobres los otros tributos involucrados en la operación en curso."; }}

		public IMI_TFGetOtrosTrib_ClassInterface Input { get; protected set; }
		public IMO_TFGetOtrosTrib_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_TFGetOtrosTrib();
			Output = new MO_TFGetOtrosTrib();
		}

		// Ctor
		public CMD_TFGetOtrosTrib()
		{
			SetDefaults();
		}
	}

}
