// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_DiagEquipo.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_DiagEquipo_ClassInterface
	{
		bool Estacion { get; set; }
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_DiagEquipo 
		: MInput
		, IMI_DiagEquipo_ClassInterface
	{
		public bool Estacion { get; set; }
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				if(Estacion) extension |= 0x01;
				SetOpcode(0x0201, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_DiagEquipo_ClassInterface
	{

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_DiagEquipo  
		: MOutput
		, IMO_DiagEquipo_ClassInterface
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_DiagEquipo_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_DiagEquipo_ClassInterface Input { get; }
		IMO_DiagEquipo_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_DiagEquipo 
	    : CMD_Generic
		, ICMD_DiagEquipo_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DiagEquipo"; }}
		public override int Opcode { get { return 0x0201; }}
		public override string Description { get { return "Imprime un documento con las características del mecanismo impresor."; }}

		public IMI_DiagEquipo_ClassInterface Input { get; protected set; }
		public IMO_DiagEquipo_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_DiagEquipo();
			Output = new MO_DiagEquipo();
		}

		// Ctor
		public CMD_DiagEquipo()
		{
			SetDefaults();
		}
	}

}
