// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2022 - Federico Villafañes (federvillaf@hotmail.com)
// http://www.moretti.com.ar y Federico Villafañes - All Rights Reserved

// CMD_ObtenerInfoCertif.cs - Automatic processing of commands.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace FiscalProto
{
	public interface IMI_ObtenerInfoCertif_ClassInterface
	{
		byte[] GetCommand();
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MI_ObtenerInfoCertif 
		: MInput
		, IMI_ObtenerInfoCertif_ClassInterface
	{
		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x0240, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}


	public interface IMO_ObtenerInfoCertif_ClassInterface
	{
		bool RootCertValid { get; set; }
		int RootCertFechaInicio { get; set; }
		int RootCertFechaFinal { get; set; }
		bool CFCertValid { get; set; }
		int CFCertFechaInicio { get; set; }
		int CFCertFechaFinal { get; set; }
		int Fecha { get; set; }
		string Serie { get; set; }

        string PrinterStatus { get; }
		string FiscalStatus { get; }
		int ErrorCodeInt { get; }

		void SetFromCommand(byte[] bindata);
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class MO_ObtenerInfoCertif  
		: MOutput
		, IMO_ObtenerInfoCertif_ClassInterface
	{
		public bool RootCertValid { get; set; }
		public int RootCertFechaInicio { get; set; }
		public int RootCertFechaFinal { get; set; }
		public bool CFCertValid { get; set; }
		public int CFCertFechaInicio { get; set; }
		public int CFCertFechaFinal { get; set; }
		public int Fecha { get; set; }
		public string Serie { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					RootCertValid = Extract_Y(data, 1, false);
					RootCertFechaInicio = Extract_D(data, 6, false);
					RootCertFechaFinal = Extract_D(data, 6, false);
					CFCertValid = Extract_Y(data, 1, false);
					CFCertFechaInicio = Extract_D(data, 6, false);
					CFCertFechaFinal = Extract_D(data, 6, false);
					Fecha = Extract_D(data, 6, false);
					Serie = Extract_A(data, 16, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}


	public interface ICMD_ObtenerInfoCertif_ClassInterface
	{
		CmdStatus Status {  get ; }
		string Nombre { get; }
		int Opcode { get; }
		string Description { get; }

		IMI_ObtenerInfoCertif_ClassInterface Input { get; }
		IMO_ObtenerInfoCertif_ClassInterface Output { get; }
	}

    [ClassInterface(ClassInterfaceType.None)]
	public class CMD_ObtenerInfoCertif 
	    : CMD_Generic
		, ICMD_ObtenerInfoCertif_ClassInterface
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "ObtenerInfoCertif"; }}
		public override int Opcode { get { return 0x0240; }}
		public override string Description { get { return "Obtiene información acerca de los certificados instalados en el controlador fiscal."; }}

		public IMI_ObtenerInfoCertif_ClassInterface Input { get; protected set; }
		public IMO_ObtenerInfoCertif_ClassInterface Output { get; protected set; }

		public void SetDefaults()
		{
			Input = new MI_ObtenerInfoCertif();
			Output = new MO_ObtenerInfoCertif();
		}

		// Ctor
		public CMD_ObtenerInfoCertif()
		{
			SetDefaults();
		}
	}

}
