// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_DBEnumEnd.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Bases_de_Datos
{
	public class MI_DBEnumEnd : MInput
	{

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				SetOpcode(0x9108, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_DBEnumEnd  : MOutput
	{

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_DBEnumEnd 
	    : CMD_CommandBase<MI_DBEnumEnd, MO_DBEnumEnd>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DBEnumEnd"; }}
		public override int Opcode { get { return 0x9108; }}
		public override string Description { get { return "Finaliza (o cancela) la descarga de archivos desde la REGISTRADORA a la PC."; }}

		// Ctor
		public CMD_DBEnumEnd()
		{
			Input = new MI_DBEnumEnd();
			Output = new MO_DBEnumEnd();
		}
	}
}
