// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_DBNewRecord.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Bases_de_Datos
{
	public class MI_DBNewRecord : MInput
	{

		[Description("Indica la tabla que se usara"), Category("Extension")]
		public DBNR_Tabla Tabla { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				extension |= (((int) Tabla) & 0x0007);
				SetOpcode(0x9102, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_DBNewRecord  : MOutput
	{

		[Description("Codigo (clave principal) asignada."), Category("Datos"), ReadOnly(true)]
		public int key { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					key = Extract_N(data, 12, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_DBNewRecord 
	    : CMD_CommandBase<MI_DBNewRecord, MO_DBNewRecord>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DBNewRecord"; }}
		public override int Opcode { get { return 0x9102; }}
		public override string Description { get { return "Crea un nuevo registro en la tabla que se indica."; }}

		// Ctor
		public CMD_DBNewRecord()
		{
			Input = new MI_DBNewRecord();
			Output = new MO_DBNewRecord();
		}
	}

	public enum DBNR_Tabla 
	{
		Plu = 0,	// 000
		Clientes = 1,	// 001
		Cajeros = 2,	// 010
		MPagos = 3,	// 011
		Rubros = 4,	// 100
	};
}
