// [auto-generated]
// This file was autogenerated by a tool.
// Please, don't edit it directly. Else, your changes could be lost next time the tool is executed.
// If you need to touch this file, remove the [auto-generated] key at top. Then, the tool will skip the regeneration of this file.
//
// Copyright (c) 2017 - Andres Moretti e Hijos S.A - Argentina
// http://www.moretti.com.ar - All Rights Reserved

// CMD_DBTabla.cs - Automatic processing of commands.

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace FiscalProto.Bases_de_Datos
{
	public class MI_DBTabla : MInput
	{

		[Description("Indica la tabla que se usara"), Category("Extension")]
		public DBT_Tabla Tabla { get; set; }

		public override byte[] GetCommand()
		{
			Error = string.Empty;
			var list = new List<byte>();
			try
			{
				int extension = 0;
				extension |= (((int) Tabla) & 0x0007);
				SetOpcode(0x9150, extension, list);
			}
			catch(Exception ex) { Error = ex.Message; list.Clear(); }
			return list.ToArray();
		}
	}

	public class MO_DBTabla  : MOutput
	{

		[Description("Cantidad de filas en la tabla indicada."), Category("Datos"), ReadOnly(true)]
		public int cantidad { get; set; }

		[Description("Datos de la tabla solicitada."), Category("Datos"), ReadOnly(true)]
		public string datos { get; set; }

		public override void SetFromCommand(byte[] bindata)
		{
			Error = string.Empty;
		    var data = new BinReader(bindata);
			try
			{
				ParseAnswerHeader(data);
                if(this.ErrorCodeInt == 0)
				{
					cantidad = Extract_N(data, 12, false);
					datos = Extract_P(data, 5000, false);
				}
			}
			catch(Exception ex) { Error = ex.Message; }
		}
	}

	public class CMD_DBTabla 
	    : CMD_CommandBase<MI_DBTabla, MO_DBTabla>
	{
		public override CmdStatus Status {  get { return CmdStatus.Listo; }}
		public override string Nombre { get { return "DBTabla"; }}
		public override int Opcode { get { return 0x9150; }}
		public override string Description { get { return "Obtiene información de una tabla del sistema."; }}

		// Ctor
		public CMD_DBTabla()
		{
			Input = new MI_DBTabla();
			Output = new MO_DBTabla();
		}
	}

	public enum DBT_Tabla 
	{
		Iva = 0,	// 000
		OtrosImpuestos = 1,	// 001
	};
}
